### ISSUE TITLE
What's missing for this to work on Apple M1?

### ISSUE THREAD

**Issue by yay** [DanielGavin/ols#104]

**Comment by DanielGavin** [comment]
Hey,

It's in the `core:os` code there seems to be issues.  It has nothing to do with `ols` itself

Example of where it doesn't work:

```
package main 


import "core:fmt"
import "core:os"
import "core:mem"
import "core:path/filepath"
import "core:strings"
import "core:runtime"


walk_it :: proc(info: os.File_Info, in_err: os.Errno) -> (err: os.Errno, skip_dir: bool) {
    if info.is_dir {
        return 0, false
    }

    fmt.println(info.fullpath)


    return 0, false
}



main :: proc() {

    filepath.walk("../Odin/core", walk_it)

}
```

**Comment by yay** [comment]
Hmm, I don't even see simple things forking, like cmd-clicking on `println` in `fmt.println`.

The `ols.json` contents are as follows.

```
{
    "collections": [
        {
            "name": "core",
            "path": "/Users/yay/bin/Odin/core"
        }
    ],
    "enable_document_symbols": true,
    "enable_semantic_tokens": false,
    "enable_hover": true,
    "enable_snippets": true
}
```

**Comment by DanielGavin** [comment]
If you are on M1, then I would expect only in file completion to work.

**Comment by yay** [comment]
Yeah, that sounds about right. Thanks.

**Comment by DanielGavin** [comment]
It should only fail on M1. Other people have ussed intel macs without issue.

**Comment by DanielGavin** [comment]
I think something is wrong in the binding of the Darwin functions in https://github.com/odin-lang/Odin/blob/master/core/os/os_darwin.odin

Maybe the structs are not the same as with the intel version.

**Comment by DanielGavin** [comment]
This also confuses me.

Is there a reason to do this:

```
@(link_name="fdopendir$INODE64") _unix_fdopendir_amd64 :: proc(fd: Handle) -> Dir ---
@(link_name="readdir_r$INODE64") _unix_readdir_r_amd64 :: proc(dirp: Dir, entry: ^Dirent, result: ^^Dirent) -> c.int ---
@(link_name="fdopendir")         _unix_fdopendir_arm64 :: proc(fd: Handle) -> Dir ---
@(link_name="readdir_r")         _unix_readdir_r_arm64 :: proc(dirp: Dir, entry: ^Dirent, result: ^^Dirent) -> c.int ---
```

I would assume this readdir_r$INODE64 is equally correct on arm64. Try to rename them to that for arm64 aswell.

**Comment by yay** [comment]
> 

I thought so too, but they seem to be the same:

Swift declarations:
```
public func open(_ path: UnsafePointer<CChar>, _ oflag: Int32) -> Int32
public func fcntl(_ fd: Int32, _ cmd: Int32, _ ptr: UnsafeMutableRawPointer) -> Int32
```
Odin's:
```
Handle    :: distinct i32
@(link_name="open")             _unix_open          :: proc(path: cstring, flags: i32, mode: u16) -> Handle ---
@(link_name="fcntl")            _unix_fcntl         :: proc(fd: Handle, cmd: c.int, buf: ^byte) -> c.int ---
```

I tried removing `mode: u16` from `_unix_open` just now but that didn't help either.

**Comment by yay** [comment]
I referenced this issue in `compiler-dev` on Discord, so hopefully someone will be able to chime in.

**Comment by DanielGavin** [comment]
Great. I also told Bill about it in the ols channel with an example.

**Comment by yay** [comment]
I started digging into this to try to figure out how Odin deals with overloaded foreign imports.
And if you do: `nm -gU /usr/lib/system/libsystem_kernel.dylib` to print out the symbol table, there's multiple definitions in there, including `_fcntl` and `___fcntl`.

When one does `@(link_name = "fcntl")` in Odin, it seems the compiler prepends a single `_` by default, so to get the `___fcntl` one has to use `@(link_name = "__fcntl")`.

```
when ODIN_OS == .Darwin {
	// foreign import libc "system:System.framework"
	foreign import libc "System.framework"
}

Handle :: distinct i32

foreign libc {
	@(link_name = "open")
	open :: proc(path: cstring, flags: i32, mode: u16) -> Handle ---
	// @(link_name = "open")
	// open :: proc(path: cstring, flags: i32) -> Handle ---
	// @(link_name = "close")
	// close :: proc(handle: Handle) -> c.int --- // Odin doesn't specify the return value for `close`
	// @(link_name="close")            _unix_close         :: proc(handle: Handle) ---
	@(link_name = "__fcntl")
	fcntl :: proc(fd: Handle, cmd: c.int, buf: ^byte) -> c.int ---
}

main :: proc() {
    fd := open("/bin/ls", 0, 0)
    fmt.println("File descriptor:", fd)
    
    buf: [256]byte
    fcntl_value := fcntl(fd, os.F_GETPATH, &buf[0])
    fmt.println("`fcntl` value:", fcntl_value)
    fmt.println("`fcntl` buf:", string(buf[:]))
}
```

**Comment by yay** [comment]
![go_to_definition](https://user-images.githubusercontent.com/1799756/168171104-f5025085-e9e5-4f4a-8e5a-7bda1619f42a.gif)

Oh yeah! Can't describe how excited I am. Awesome job on the extension @DanielGavin and your guess was correct as well!

**Comment by DanielGavin** [comment]
Awesome!

**Comment by DanielGavin** [comment]
I know someone else also is waiting to use it for M1.

**Comment by yay** [comment]
Should autocomplete and go to definition work on vendor packages?

I don't see it working here:

```
import NS "vendor:darwin/Foundation"
import SDL "vendor:sdl2"

metal_main :: proc() -> (err: ^NS.Error) {
    SDL.SetHint(SDL.HINT_RENDER_DRIVER, "metal")
    SDL.setenv("METAL_DEVICE_WRAPPER_TYPE", "1", 0)
    SDL.Init({.VIDEO})
    defer SDL.Quit()
```

**Comment by DanielGavin** [comment]
It should. Have you added to `ols.json`

`{ "name": "vendor", "path": "c:/path/to/Odin/vendor" }`?

**Comment by yay** [comment]
Awesome, thanks!

**Comment by yay** [comment]
<img width="1003" alt="Screen Shot 2022-05-12 at 11 33 12 PM" src="https://user-images.githubusercontent.com/1799756/168178665-209fbebc-a132-40c7-adca-237a8a589b74.png">

This looked weird, so I verified and the language server is indeed not closed when VS Code quits.

**Comment by DanielGavin** [comment]
That is weird. Normally vscode would close it. Could be some issue with the ols extension not shutting it down correctly on Mac.

**Comment by DanielGavin** [comment]
I made a change that might have caused an issue. You can try that.

**Comment by yay** [comment]
Nice! Yeah, that fixes it.

**Comment by yay** [comment]
Happy to see this merged!

With that out of the way, I noticed that go to definition doesn't work on statements with the`->` operator:
https://odin-lang.org/docs/overview/#--operator-selector-call-expressions

For example:

```
import MTL "vendor:darwin/Metal"

device := MTL.CreateSystemDefaultDevice()
defer device->release() // <---
```

Go to definition will work on `CreateSystemDefaultDevice` but not on `device` or `release`.

**Comment by DanielGavin** [comment]
There is indeed a bug in operator selector call expression, but the reason this is not working for Metal is because the definition of Device is hardcoded somewhere with intrinsics.

```
Object :: struct {using _: intrinsics.objc_object}

@(objc_class="MTLDevice")
Device :: struct { using _: NS.Object }
```

This means I need to add some more support for that by making my own intrinsics file, just like I did with builtin.odin.

**Comment by yay** [comment]
I guess, I can close this now. It seems to be operator selector and Darwin related but not specific to Apple silicon. Thanks for your help!
