### ISSUE TITLE
language server reliably crashes on certain code

### ISSUE THREAD

**Issue by yay** [DanielGavin/ols#110]
If you hover `context`, the language server crashes every single time:

```odin
reliable_crash :: proc() {
     for in 0..<5 {
        t := context
    }
}
```
<img width="452" alt="Screen Shot 2022-06-03 at 1 20 03 AM" src="https://user-images.githubusercontent.com/1799756/171761008-de5d6c00-31da-4352-8a80-8fbcf2a9b969.png">

**Comment by DanielGavin** [comment]
Should no longer crash.

**Comment by yay** [comment]
Much appreciated!
