### ISSUE TITLE
Formatting fails on selector expression

### ISSUE THREAD

**Issue by IanLilleyT** [DanielGavin/ols#114]
I'm using VSCode extension on commit 09fdb88

### Minimal repro:

```
package main

main :: proc() {
	Thing :: enum {
		A,
		B,
	}
	arr := [Thing]int {
		Thing.A = 0, // fails - selector expression
		.B = 0, // works - implicit selector expression
	}
}
```

I know it's better to do the implicit selector expression, but I first encountered this bug when using a selector that was a constant defined in another package. The enum is mainly for demonstration purposes.

### Error Log
```
[Trace - 12:28:12 AM] Sending request 'textDocument/formatting - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///c%3A/Users/ian/Code/odin-test/source/main.odin"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": false
    }
}


C:/Users/ian/Code/ols/src/odin/printer/visit.odin(1621:3) panic: unhandled get_node_length case &Selector_Expr{node = Expr{expr_base = Node{pos = Pos{file = C:/Users/ian/Code/odin-test/source/main.odin, offset = 86, line = 8, column = 3}, end = Pos{file = C:/Users/ian/Code/odin-test/source/main.odin, offset = 93, line = 8, column = 10}, state_flags = Node_State_Flags{}, derived = 0x227E496FBC8}, derived_expr = 0x227E496FBC8}, expr = 0x227E496FAB8, op = Token{kind = Period, text = ., pos = Pos{file = C:/Users/ian/Code/odin-test/source/main.odin, offset = 91, line = 8, column = 8}}, field = 0x227E496FB40}
[Info  - 12:28:12 AM] Connection to server got closed. Server will restart.
```

### Attempted Fix
I fixed the problem by adding the below code to `get_node_length` in `visit.odin`
```
case ^ast.Selector_Expr:
    return v.end.offset - v.pos.offset
```
An alternate but messier fix is below.
```
case ^ast.Selector_Expr:
    return v.expr.end.offset - v.expr.pos.offset + len(v.op.text) + len(v.field.name) 
```

I opened an issue instead of a pull request because I'm not sure if either of these fixes is the right thing to do. None of the other cases had to use `expr` to get the length, and I wonder what should happen if the expression spans multiple lines. But maybe that's not a problem. If the code looks good then I'm happy to open a pull request!

**Comment by DanielGavin** [comment]
When I think about it - it probably is fine just to do:
```
@(private)
get_node_length :: proc(node: ^ast.Node) -> int {
	return node.end.column - node.pos.column
}

```
This will also work with unicode, since the column is unicode based.

**Comment by DanielGavin** [comment]
But yeah the expression spanning lines might be a problem. I think it's fine just do the simple approach and implement a better one later.

**Comment by DanielGavin** [comment]
Code has been submitted. Try now.

**Comment by IanLilleyT** [comment]
Works for me! Thanks! Good call on testing unicode.

I also confirmed that an expression with newline works:

```
Thing :: enum {A}
arr := [Thing]int {
	Thing.
	A = 0,
}
```

formats to

```
Thing :: enum {A}
arr := [Thing]int {
	Thing.A = 0,
}
```

The length of the selector expression is correctly `7`


It's too bad your one-liner doesn't work, seeing how `offset` is a byte offset and `line`/`column` range is not really possible to compute for multiline expression.
