### ISSUE TITLE
Variable declared but no completion

### ISSUE THREAD

**Issue by nico-bb** [DanielGavin/ols#118]
Sometimes a declared variable does not appear in the completion and its fields are not showing up either.
This behavior seems to only happens when you declare the new variable with `new_clone(T{})`.
![Capture](https://user-images.githubusercontent.com/64324649/178527598-c7e40108-eef6-4b48-8db9-abfaaac6bd82.JPG)

**Comment by DanielGavin** [comment]
What is the implementation of new_clone? It clearly is an issue with resolving the poly signature of the function.

**Comment by DanielGavin** [comment]
Alright thanks. I'll try and find it.
