### ISSUE TITLE
ols only works for local declarations on macos

### ISSUE THREAD

**Issue by yay** [DanielGavin/ols#122]
But for example going to the definition of `println` in `fmt.println` doesn't work.

ols.json does exists:

```
{
    "collections": [
        {
            "name": "core",
            "path": "/Users/yay/projects/Odin/core"
        }
    ],
    "enable_document_symbols": true,
    "enable_semantic_tokens": false,
    "enable_hover": true,
    "enable_snippets": true
}
```

I set `"ols.trace.server": "verbose"` in `settings.json` but don't know where to look to try to figure out what might be going on. Where I can see the output?

(LLVM 14.0.6, Odin and ols built from tips of master)

**Comment by yay** [comment]
I verified that this is no longer related to https://github.com/DanielGavin/ols/issues/104

**Comment by DanielGavin** [comment]
Should now be fixed.

**Comment by yay** [comment]
Thanks! Have you pushed your changes though? I don't see any new commits.

**Comment by DanielGavin** [comment]
I fixed the bug on Odin. So you need to pull there.

**Comment by yay** [comment]
Ah, gotcha! Thanks!
