### ISSUE TITLE
VScode ols server crashing when import is missing final quote

### ISSUE THREAD

**Issue by WalterPlinge** [DanielGavin/ols#13]
### Code snippet
Missing the `"` after the `:` in an import statement, though only when there is text between the first `"` and `:`
```
package main
import "core:
```

ols.json:
```
{
    "collections": [
	{ "name": "core", "path": "C:/Odin/Odin/core/" },
        { "name": "shared", "path": "C:/Odin/Odin/shared/" }
    ],
    "thread_pool_count": 4,
    "enable_document_symbols": true,
    "enable_semantic_tokens": true,
    "enable_hover": true
}
```
### Error
Output window:
`C:/Odin/Tools/ols/src/server/documents.odin(415:30) Invalid slice indices: 6:5:6`

### VSCode info:
Version: 1.53.0-insider (system setup)
Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
Date: 2021-01-19T06:09:44.762Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by DanielGavin** [comment]
This should now be fixed.
