### ISSUE TITLE
Crash on textDocument/hover in vscode

### ISSUE THREAD

**Issue by iansimonson** [DanielGavin/ols#139]
OS: Windows 11
OLS Commit: 314f0e6497d623775b77e5f95318ec8758270d2e
Odin Version:  dev-2022-08:3469178d

OLS crashes on text hover in certain instances. When this happens vscode attempts to restart the server and send the same hover again which leads to another crash. This results in the vscode popup that ols crashed 5 times in 3 minutes.

Attached is a partially completed vulkan tutorial example which crashed on hover for a new empty function `create_graphics_pipeline (main.txt instead of .odin as github wouldn't let me upload an odin file directly)

[main.txt](https://github.com/DanielGavin/ols/files/9428961/main.txt)
[ols_crash_stack.txt](https://github.com/DanielGavin/ols/files/9428962/ols_crash_stack.txt)

Currently discussing in discord, writing here for posterity

**Comment by iansimonson** [comment]
This minimally reproduces the crash:
```odin
package main

T :: struct {}

main :: proc() {
    t, ok := foo() // crashes if hover here
    foo() // does not crash if hover
}

foo :: proc() -> (value: T, ok := true) {
    if false {
        return {}, false
    }
    return
}
```

stack trace is the same as before (from ols down at least)

**Comment by iansimonson** [comment]
Note, once the `t, ok := foo()` line exists, hovering any line later in main (but not the file level declarations) or starting completion causes the same crash

**Comment by DanielGavin** [comment]
Should now be fixed.
