### ISSUE TITLE
VScode ols crashes with proc keyword and parentheses

### ISSUE THREAD

**Issue by WalterPlinge** [DanielGavin/ols#14]
### Code snippets
Typing a character in two parentheses after `proc`, I've only tested `!`, `%`, `&` and `*`:
```
package main
main :: proc((*)) {}
````

### Error
Only got `Connection to server got closed.` in the output window

### VSCode info:
Version: 1.53.0-insider (system setup)
Commit: 32b28f6f8f9dfe36efad102cc460e14a84ba756a
Date: 2021-01-19T06:09:44.762Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by DanielGavin** [comment]
Waiting for bill to handle my PR. It's an error in the parser package.
