### ISSUE TITLE
Go to defintion not distinguishing between linux and windows OS type correctly

### ISSUE THREAD

**Issue by wil-den** [DanielGavin/ols#140]
My OS is Arch. 
I have imported the "core:os" package.
I CTRL + Click the os.open procedure and I am brought to the Windows implementation.

More than happy to take a stab at fixing it myself if you don't mind?
If so, I would have an question re debugging.

**Comment by DanielGavin** [comment]
Try to see if my new change has fixed your problem.

**Comment by wil-den** [comment]
Works like a charm. Thanks for the prompt update!
