### ISSUE TITLE
How does formatting work with LSP

### ISSUE THREAD

**Issue by samwdp** [DanielGavin/ols#141]
I have just updated to the latest build where odinfmt is now a separate binary. Previously Emacs LSP lsp-format-buffer worked when the options ```"formatter":{}``` section was in ols.json. Now with the formatter separated the LSP command to format the buffer no longer works. How do I get this working again as there is no option in the docs to allow the formatting through LSP?

**Comment by DanielGavin** [comment]
That is correct. You can do it through odinfmt.json:```
{
	"character_width": 80,
	"tabs": true,
	"tabs_width": 4
}```

**Comment by DanielGavin** [comment]
I want the configuration be done the same with or without Ols.

**Comment by samwdp** [comment]
@DanielGavin I have an ols.json in the root of my project and an odinfmt.json in the root. For some reason the LSP didn't pick it up. Restarting the LSP seemed to fix it. Strange
