### ISSUE TITLE
Not compiling with the latest version of Odin

### ISSUE THREAD

**Issue by Daemondeal** [DanielGavin/ols#150]
## Issue
ols does not compile using the latest version of Odin, giving the error:
```
/home/daem/Tools/ols/src/odin/printer/visit.odin(2294:6) Undeclared name 'Optional_Second' for type 'Proc_Tag'
```

## Possible fix

Just replacing `Optional_Second` with `Optional_Allocation_Error` and `#optional_second` with `#optional_allocator_error` is enough to make it compile again. I'm unsure if anything else gets broken by this though.

## Odin Report Output
Odin: dev-2022-09:7cd78861
OS:   Arch Linux, Linux 5.19.8-arch1-1
CPU:  Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
RAM:  15876 MiB

**Comment by DanielGavin** [comment]
Thanks for the info. Should now compile again.
