### ISSUE TITLE
Can't create connection to server

### ISSUE THREAD

**Issue by wil-den** [DanielGavin/ols#153]
[Error - 12:07:48 PM] Odin Language Server Client client: couldn't create connection to server

What am I not doing here?

**Comment by DanielGavin** [comment]
Hey.

Are you on Linux/Darwin?

There was an issue with a `Odin` change. This has now been fixed. Try again.

**Comment by wil-den** [comment]
Hi, 

Yes I am running Arch. Apologies should have mentioned that.
I will update and try again.

**Comment by DanielGavin** [comment]
It's important that you update `Odin`. Didn't mention what you had to update.

**Comment by wil-den** [comment]
Thanks. I have got the latest from `Odin` master and rebuilt. 

Do i need to install the ols server separately to the extension?
This morning I cloned your repo and built it. I pointed `ols.server.path` to the executable. I tried this as I was getting errors about command 'ols.start' not found so assumed it was because the `ols.server.path` was set to `NULL`.

**Comment by DanielGavin** [comment]
Do you don't have to. Just let `ols.server.path` be null and open a `.odin` file, it should ask if you want to install the server.

**Comment by wil-den** [comment]
Thanks, but it is not asking to install the server.

**Comment by DanielGavin** [comment]
It could be it's already installed then. Do you have completion?

**Comment by wil-den** [comment]
I am not at my computer right now so can't check but it makes sense that it
was installed already as I was using your extension before I had the vscode
upgrade issue.
Where would your extension install it by default? Can check when I get back.

Thanks for the quick replies. Much appreciated btw.

**Comment by DanielGavin** [comment]
You can check the log window: 
![image](https://user-images.githubusercontent.com/5999133/191505878-4e86f5ce-f224-419a-8d93-f641fa07437e.png)

**Comment by wil-den** [comment]
So, i rebooted and I get a different issue. ols is reporting that Odin is not on my path environment. Problem is that I know it is. 
➜  ~ which odin
/home/shared/cloned.repos/Odin/odin

Any ideas?

**Comment by wil-den** [comment]
I have completion but the extension is reporting errors. I apologise for wasting your time on this.

Confused as to why I am getting these errors and completion is available. 
Anyway, thanks for the help. I am going to close this now.
