### ISSUE TITLE
Code completion should not be performed in `""`

### ISSUE THREAD

**Issue by C-BJ** [DanielGavin/ols#161]

**Comment by C-BJ** [comment]
This is a function suggestion
I think

**Comment by DanielGavin** [comment]
If it's a bug report, can you please show the text that doesn't complete? 

It could also be you haven't set up `ols` correctly, if nothing completes.

**Comment by C-BJ** [comment]
![image](https://user-images.githubusercontent.com/62678643/199518199-54cfec3a-39c0-4005-9547-f2655053c715.png)
I'm not really familiar with Odin, but I don't think there should be any tips

**Comment by DanielGavin** [comment]
You are correct. Completion shouldn't really happen in `""`.

**Comment by DanielGavin** [comment]
It should now be fixed.
