### ISSUE TITLE
Erreur: build.bat

### ISSUE THREAD

**Issue by hirochirac** [DanielGavin/ols#166]
Lorsque je lance la commande build.bat, j'obtiens le message d'erreur:
/ols-master/src/common/allocator.odin(70:16) Undeclared name 'Alloc_Non_Zeroed' for type 'Allocator_Mode'
Comment y remédier svp?

Cordialement.

**Comment by DanielGavin** [comment]
You have to use the latest Odin version. That is something that was changed recently in Odin.

**Comment by hirochirac** [comment]
I tried again with the lastest odin version (dev-2022-11-nightly:382bd876). The same error reappeared.

**Comment by DanielGavin** [comment]
Strange. Not sure how and when Odin does its nightly. But it works on the master branch of Odin.

You can use my latest release instead: https://github.com/DanielGavin/ols/releases/tag/nightly

What is your platform?

**Comment by hirochirac** [comment]
Hi,
That's working.
Thx for helping me
