### ISSUE TITLE
Crash with parapoly proc in another file that returns a matrix

### ISSUE THREAD

**Issue by Despacito696969** [DanielGavin/ols#168]
`main.odin`
```odin
package main

main :: proc()
{
   foo := wait(f32)
}
```

`main2.odin`
```odin
package main

wait :: proc($T: typeid) -> matrix[3, 3]T 
{
   return {}
}
```

If you try to add a space between `->` and `matrix` in main2.odin and then in main.odin after the declaration of `foo` try typing `f`, ols will crash.

**Comment by DanielGavin** [comment]
Fixed.
