### ISSUE TITLE
odinfmt misplaces the closing brace on a for ... do if .. loop

### ISSUE THREAD

**Issue by jrfondren** [DanielGavin/ols#169]
This program correctly prints 5, looping over the potential members of a bit_set and then printing them if found in it:

```odin
package main

import "core:fmt"

main :: proc() {
	bag: bit_set[0 ..< 10] = {5}
	for x in 0 ..< 10 do if x in bag {
			fmt.println(x)
		}
}
```

formatting is with a freshly built odinfmt from master.

**Comment by DanielGavin** [comment]
This is now fixed.
