### ISSUE TITLE
OLS crashes when writing procedure group overloads with shared prefix

### ISSUE THREAD

**Issue by iansimonson** [DanielGavin/ols#171]
OLS version is from commit `532f4bf` but was occurring with previous versions also

I ran into this several times when updating a procedure to be a procedure group with a couple overloads. The crash appears to be related to all the procedures having the same prefix of `foo` in this case. It will occur occasionally with just a single main.odin file, however I can get it to happen relatively deterministically with the following setup:
```
ols_test/
  main.odin
  pkg/
    pkg.odin
```
main.odin:
```odin
package main
import "pkg"
main :: proc() {
  pkg.foo(3)
}
```
pkg.odin
```odin
package pkg
foo_int :: proc(a: int) -> int {
  return a
}

//typing the following causes the crash:
foo :: proc{foo} // crashes here
```

the crash occurs by typing in `pkg.odin`: `foo :: proc{foo}` (note the closing brace is auto-inserted by vscode, the cursor is right after the second `foo` i.e. I'm trying to type `foo_int` but OLS crashes immediately at this point. If I restart OLS I can complete the word `foo_int`, however it will crash when `foo` is typed again (e.g. adding a `foo_string` to the group)

**Comment by DanielGavin** [comment]
Should now be fixed.
