### ISSUE TITLE
Saving source file causes ols errors to go away.  

### ISSUE THREAD

**Issue by Vaxeral** [DanielGavin/ols#177]
After saving my odin source file the errors that lsp intially report with my code go away.  I can bring them back be typing anything.

**Comment by DanielGavin** [comment]
It's because you are getting different errors from different systems. When typing it's from the parser, and then saving it's from `odin check`.

**Comment by krixano** [comment]
This is good to know. I always get parser errors on `if ... do ....` statements, which disappear after saving. So perhaps `core:odin/parser` isn't working well with `if do` statements.
