### ISSUE TITLE
selector call expressions not working

### ISSUE THREAD

**Issue by GideonUng** [DanielGavin/ols#18]
Not sure how recent this addition to odin or if its sure to stay in the language but ols seems to not know about it yet.

`foo->bar()` syntax

![image](https://user-images.githubusercontent.com/5054701/108408927-ec5ff480-7225-11eb-8c64-64526f2d1b68.png)

**Comment by DanielGavin** [comment]
This hasn't been added yet. It's not a well advertised feature of Odin it seems. I'll put into my priority list.

**Comment by DanielGavin** [comment]
This has now been implemented. Feel free to create another issue if it doesn't work correctly.
