### ISSUE TITLE
odinfmt-disable space sensitivity

### ISSUE THREAD

**Issue by jon-lipstate** [DanielGavin/ols#180]
the odinfmt disable seems to be space-sensitive, I'd like to request it eats spaces for the line such that all of the following versions work:
```odin
//odinfmt: disable <- works
//odinfmt:disable <- not works
// odinfmt: disable <- not works
// odinfmt:disable <- not works
```

**Comment by jakubtomsu** [comment]
This would be a very nice change. I always forget which version it is, and after a few attempts I usually end up searching for it on discord.

**Comment by DanielGavin** [comment]
Should be fixed. I now remove all spaces when looking for `//odinfmt:disable/enable`.
