### ISSUE TITLE
Unable to build ols on Windows

### ISSUE THREAD

**Issue by hristo-kanchev** [DanielGavin/ols#182]
Description:
Unable to build `ols` on Windows 11 by running the `build.bat` command.

I am getting the following error when executing the command:
```
ols/src/common/util_windows.odin(105:16) Error: 'STARTUPINFO' is not declared by 'win32'
        startup_info: win32.STARTUPINFO
                      ^~~~~~~~~~~~~~~~^
        Suggestion: Did you mean?
                STARTUPINFOW
```

I posted this issue on the Odin discord and I was given the advice to add the "W" suffix.
After doing that the build went through and now I am able to use the LSP.

**Comment by DanielGavin** [comment]
Fixed.

**Comment by ethan-tqa** [comment]
It's funny, I have the exact opposite problem, so deleting the 'W' worked for me. Was building on windows 10 64-bit

**Comment by DanielGavin** [comment]
@ethan-tqa  It's because you have an older version of `Odin`. I try to maintain `ols` with the latest master branch.
