### ISSUE TITLE
#soa pointer qualifier just gets removed

### ISSUE THREAD

**Issue by jakubtomsu** [DanielGavin/ols#184]
When I have a SOA pointer, the first `#soa` gets removed.

 e.g.
```odin
#soa^#soa[1024]Foo
```
gets turned into:
```odin
^#soa[1024]Foo
```

Of course this always results in an compile-time error and then I'm forced to use `//odinfmt: disable`.

**Comment by DanielGavin** [comment]
Seems like a bug in `"core:odin/parser"`. Pointer_Type.tag is null.

Will have to check it.

**Comment by DanielGavin** [comment]
Should be fixed. It atleast seems to work for me. Open it again if it doesn't work.
