### ISSUE TITLE
How to change indentation from tab to spaces?

### ISSUE THREAD

**Issue by nmsobri** [DanielGavin/ols#185]
I have read the doc, and here is my `odinfmt.json` config:

`{
	"character_width": 100,
	"tabs": "spaces",
	"spaces": 2
}`

but still, it didn't take any effect..help pls

**Comment by nmsobri** [comment]
Nvm, suddenly found it

**Comment by algmyr** [comment]
For anyone finding this issue in the future, the problem is that the config above has
```
"tabs": "spaces"
```
which should be
```
"tabs": false
```
