### ISSUE TITLE
Adding emacs to clients.

### ISSUE THREAD

**Issue by SergLoff** [DanielGavin/ols#19]
Hello and thanks for your work on ols!
Sorry for adding this as an issue I didn't know where else to put it and is such a small thing that a full pull request seemed like too much.
I've been testing ols on linux with [odin-mode](https://github.com/mattt-b/odin-mode) (found in the "odin libs" section of the odin wiki) and [lsp-mode](https://github.com/emacs-lsp/lsp-mode/). Completion and hovering are working great, goto-definition of functions does make the server crash sometimes, (with exit code "1"), but other than that I haven't had any issues.
So I was wondering if you might like to add emacs to the list of clients in the README file.
If you decide to add it, here's the config:

```elisp
;; With odin-mode (https://github.com/mattt-b/odin-mode) and lsp-mode already added to your init.el of course!.
(setq-default lsp-auto-guess-root t) ;; if you work with Projectile/project.el this will help find the ols.json file.
(defvar lsp-language-id-configuration '((odin-mode . "odin")))
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "/path/to/ols/executable")
                  :major-modes '(odin-mode)
                  :server-id 'ols
                  :multi-root t)) ;; This is just so lsp-mode sends the "workspaceFolders" param to the server.
(add-hook 'odin-mode-hook #'lsp)
```
Please, let me know if you need any more info.
Cheers!.

**Comment by DanielGavin** [comment]
That's perfect. I was thinking of the emacs client, but my skills in configuring emacs is lacking :)

Regarding the goto-definition crashing, if it is easy to reproduce just make an issue on it.

**Comment by DanielGavin** [comment]
Emacs config has now been added
