### ISSUE TITLE
it only  displays error after the file has been saved

### ISSUE THREAD

**Issue by Victorisikwe** [DanielGavin/ols#191]
i don't get any error reports while i am typing, it only shows up whenl i save the file. i am using neovim lsp.

**Comment by DanielGavin** [comment]
Not a bug. Currently the `odin check` gets called after saving. There is also some error reporting on syntax that can happen when typing from `core:odin/parser`, but the real error comes after saving.

**Comment by Victorisikwe** [comment]
okay thanks.
