### ISSUE TITLE
Any chance of adding Helix to the list of compatible clients in the README?

### ISSUE THREAD

**Issue by 7ombie** [DanielGavin/ols#197]
Helix is becoming more popular, and supports Odin out the box. It'd be nice to see it mentioned in the README.

Thanks, either way.

**Comment by DanielGavin** [comment]
Sure. Go ahead. I rely on people using the editors to add that README information.

**Comment by DanielGavin** [comment]
It does seem like it's mentioned, but just no link to it:
https://github.com/DanielGavin/ols#helix
