### ISSUE TITLE
type of slice variable shows up as an array

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#198]
odin version: dev-2023-06:4c17e2e9

![image](https://github.com/DanielGavin/ols/assets/24491503/495798ef-5f24-4081-977c-5fe603c13b9a)

the type of `buf_slice` when hovered shows up as `[420]byte` instead of `[]byte`

**Comment by DanielGavin** [comment]
Should now be fixed.

**Comment by thetarnav** [comment]
yup works great now, thanks!
