### ISSUE TITLE
Failing LS request with error "Clone type Unhandled node kind: Type_Cast"

### ISSUE THREAD

**Issue by dresswithpockets** [DanielGavin/ols#20]
Running the latest commit of ols against one of my projects resulted in LS request failure with error:
```
Clone type Unhandled node kind: Type_Cast
```

I made this change
```diff
@@ -214,6 +214,10 @@ clone_node :: proc(node: ^ast.Node, allocator: mem.Allocator, unique_strings: ^m
        case Helper_Type:
                r := cast(^Helper_Type)res;
                r.type = clone_type(r.type, allocator, unique_strings);
+       case Type_Cast:
+               r := cast(^Type_Cast)res;
+               r.type = clone_type(r.type, allocator, unique_strings);
+               r.expr = clone_type(r.expr, allocator, unique_strings);
        case:
                panic(fmt.aprintf("Clone type Unhandled node kind: %T", node.derived));
        }
```

which ultimately allowed the failing LS request to succeed. I'm largely unfamiliar with the purpose of `clone_node` and the inner workings of this project, so I do not know if this is a correct implementation for `Type_Cast` here, and do not know if in reality this is just a bandaid over a different bug in OLS which resulted in this faulty call.

Is this a valid fix? If so I'll happily move this into a PR, otherwise I felt this would be better as an issue for discussion's sake.

**Comment by DanielGavin** [comment]
This is the correct solution. I just recently moved the default case to a panic(as you noticed), since if I forget to clone it, you might end up with a segmentation fault later.

You can make a PR  👍

**Comment by dresswithpockets** [comment]
> You can make a PR 👍

Will do!
