### ISSUE TITLE
Compilation fails on Linux (Ubuntu 22.04 LTS)

### ISSUE THREAD

**Issue by moeenn** [DanielGavin/ols#200]
I have downloaded and build the Odin language compiler on my system. There are no errors when building the compiler. I have tried to compile OLS as instructed in the README.md as follows

```bash
$ ./build.sh
```

The system outputs the following errors.

![image](https://github.com/DanielGavin/ols/assets/7567765/a1d721e5-3ead-4831-919e-ded83150fbd1)

Please provide some assistance in resolving these errors.

**Comment by DanielGavin** [comment]
This is because your `Odin` version is old. Try the master branch of `Odin`.

**Comment by moeenn** [comment]
@DanielGavin I don't know how I missed this, I feel so silly. The issue is resolved now.
