### ISSUE TITLE
ols crash from a bad prodecure declaration syntax

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#203]
declaring a procedure like this, and saving the file will crash the ols:
```odin
//      ↓  wrong assignment symbol
my_proc = proc(a: string) {}
```

**Comment by DanielGavin** [comment]
Probably the formatter crashing on save - I'll try to make it more robust. It shouldn't format at all with incorrect syntax.

**Comment by DanielGavin** [comment]
Fixed.
