### ISSUE TITLE
semantic tokens overwrite escaped chars

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#204]
with:
![image](https://github.com/DanielGavin/ols/assets/24491503/7ff48e2c-867a-40c5-a7e2-7e98779c30ec)

without:
![image](https://github.com/DanielGavin/ols/assets/24491503/d91fb582-1ece-48bb-a5ef-a18e69555d6a)

typescript for reference:
![image](https://github.com/DanielGavin/ols/assets/24491503/12184257-9db8-43d9-927a-040b4bc3f664)

**Comment by DanielGavin** [comment]
I'm planning on removing all the semantic stuff on what should be done with grammar files / tree-sitters. And only give the really semantic needed tokens which will be for identifiers.

**Comment by DanielGavin** [comment]
Fixed.
