### ISSUE TITLE
Indexing workspace is not implicit

### ISSUE THREAD

**Issue by dresswithpockets** [DanielGavin/ols#21]
In order for ols to index my project's code, I've had to add this entry into `collections` in ols.json:
```json
{"name": "", "path": "."}
```
is this by design? This isn't mentioned in the readme so I'm uncertain if this is a bug or intended.

**Comment by DanielGavin** [comment]
I wouldn't really call it a bug, it's not exactly how I intended on it being used. I generally expected project setups to be as follows: src/main.odin
src/my_collection/other_code.odin

Then you would set it up with {"name": "shared", "path": "src"}

But if it works for you without the need to specify the collection and you just want to use everything relative, then that is fine for me. 

I had actually thought of separating the collection config from indexing, and instead just specifying all the root folders to index from, and if you wanted to use collections you had to specify the path of them.

i.e. In the new system you would just have one index directory and zero collections.

**Comment by dresswithpockets** [comment]
Since I keep my core and shared collections near the odin executable, in a similar way as to how one might work with a Go workspace, I'm totally fine with just using `{"name": "", "path": "."}` whenever i need the ls to index my project in a different location, it doesn't impact my workflow really, but it is unusual that the ls doesnt default to indexing the workspace in the first place - which is how most other ls's work. I'd say as long as this oddity is documented it doesn't really matter which way you swing.

**Comment by DanielGavin** [comment]
There is no reason why I couldn't just index the workspace by default. I'll keep this issue open, and close it when I get around to indexing the workspace implicitly.

**Comment by dresswithpockets** [comment]
Cool, I appreciate the work!
