### ISSUE TITLE
procedure aliases missing information

### ISSUE THREAD

**Issue by ryuukk** [DanielGavin/ols#216]
Example:

It should show that it is a proc with parenthesis ``()`` and the return type

```odin
Init      :: glfw.Init
```

```odin
/*** Functions ***/
@(default_calling_convention="c", link_prefix="glfw")
foreign glfw {
	Init      :: proc() -> c.int ---
}
```

![image](https://github.com/DanielGavin/ols/assets/44361234/1254dd7f-a1e1-4e35-a51f-74eaa62a7aa2)

![image](https://github.com/DanielGavin/ols/assets/44361234/3cc22c1d-e618-4c77-9b66-0f7273fa0c8e)

**Comment by DanielGavin** [comment]
Should be fixed
