### ISSUE TITLE
feature: integrate odinfmt to be used via LSP's command

### ISSUE THREAD

**Issue by ryuukk** [DanielGavin/ols#217]
- being able to format a single file/folder
- being able to format the selection
- configurable via editor setting

I'll try to send a PR

**Comment by DanielGavin** [comment]
It is already possible to use `odinfmt` with LSP command.

**Comment by DanielGavin** [comment]
Doesn't sublime send the config before `workspace/didChangeConfiguration` with 
```
interface InitializeParams extends WorkDoneProgressParams {
/**
* User provided initialization options.
*/
initializationOptions?: LSPAny;
```
on initiialize?
