### ISSUE TITLE
"expected a comma, got a newline" incorrect syntax error

### ISSUE THREAD

**Issue by ryuukk** [DanielGavin/ols#224]
![image](https://github.com/DanielGavin/ols/assets/44361234/282615f1-a10d-4349-ae73-500f349be023)

I get this A LOT, it goes away when the file is saved

There must be a problem in the logic somewhere

I couldn't find where this code happens in ols, do you mind helping me locate it?

**Comment by DanielGavin** [comment]
It's the syntax parser givings errors on typing. It's not in ols, but in `core:odin/parser`
