### ISSUE TITLE
more clear instructions on how to install on emacs/doom emacs

### ISSUE THREAD

**Issue by mrutyunjayan** [DanielGavin/ols#230]
I've installed odin-mode and lsp-mode, but idk what to do with the instructions given on the readme file. Wehere am I supposed to copy and paste the given installation script? Would it be possible to clarify what to do with the script, I've tried asking on various forums for advice. Thank you!

**Comment by DanielGavin** [comment]
I have no knowledge of emacs. Hopefully something could contribute with this problem.

**Comment by hasanyasin** [comment]
Hey @mrutyunjayan,

With Doom, it should be in  your `config.el`, probably one of `~/.doom.d/config.el`. If you are using a recent version with default bindings, on the welcome screen, do 
`space`, `f`, `p`
or select "Open private configuration" from the menu. You will show see the list of files in your `doom.d` folder from where you can simply open `config.el`.

**Comment by mrutyunjayan** [comment]
> Hey @mrutyunjayan,
> 
> With Doom, it should be in your `config.el`, probably `~/.doom.d/config.el`. If you are using a recent version with default bindings, on the welcome screen, do `space`, `f`, `p` or select "Open private configuration" from the menu. You will show see the list of files in your `doom.d` folder from where you can simply open `config.el`.

Hey @hasanyasin thank you for the reply. I've tried that but it breaks my doom emacs when I try to update to using the new config.el....

at the start of the instrictions, it says :

"With odin-mode (https://github.com/mattt-b/odin-mode) and lsp-mode already added to your init.el of course!."

I maybe doing something wrong here - I have lsp-mode added, but how do I add odin-mode?

**Comment by MarcusE1W** [comment]
I guess there are more elegant ways to do it, but for now this line installs Odin-mode for me:
```
load (expand-file-name "~/.local/odin-mode/odin-mode.el"))
```

You have to change the path to where your Odin-mode is downloaded.

**Comment by MarcusE1W** [comment]
You could also consider to use the package `Eglot` which is an alternative to lisp-mode and from Emacs 29 onwards is part of Emacs.

The simplest config for Eglot is here: https://github.com/DanielGavin/ols/issues/237

**Comment by DanielGavin** [comment]
Closing. Feel free to make a PR for more emacs documentation.
