### ISSUE TITLE
Error parsing varargs?

### ISSUE THREAD

**Issue by hwchen** [DanielGavin/ols#235]
Looks like parsing fails when passing varargs to a function.

One example is running ols on https://github.com/odin-lang/Odin/blob/master/core/fmt/fmt_os.odin

Initially, ols will error at https://github.com/odin-lang/Odin/blob/9453b2387b2cc7c473547997703c305e7982f5e4/core/fmt/fmt_os.odin#L17, then the error goes away when saving (because `odin check` succeeds, I think).

```
1. expected ')' after argument list, got 'identifier'
2. expected a statement, got =
```

Relatedly, this might be affecting autocomplete. On the file, `print` https://github.com/odin-lang/Odin/blob/9453b2387b2cc7c473547997703c305e7982f5e4/core/fmt/fmt_os.odin#L64 will autocomplete, but the next proc `println` will not. But I'm not sure, since there are earlier errors but all procs above `print` autocomplete.

**Comment by hwchen** [comment]
Looks like this can be fixed in `core:odin/parser` I'll submit a PR there.

**Comment by DanielGavin** [comment]
I assume it is now fixed. Open it if not.

**Comment by hwchen** [comment]
Yes, looks like it's fixed.
