### ISSUE TITLE
emacs29 use-package eglot

### ISSUE THREAD

**Issue by MarcusE1W** [DanielGavin/ols#237]
Hi.

Thanks for the great package :-)
Now that emacs 29 is officially out and supports out of the box  `use-package` for package configuration and `eglot` to access the language server I have started usine this config in emacs.

```
(use-package eglot
  :ensure t
  :config
  (add-to-list 'eglot-server-programs '(odin-mode . ("ols")))
  :hook
  ((odin-mode . eglot-ensure))
  )
```
It seems to work fine for me on Linux. `ols`has to be in the path.

I noticed that the config for lsp-mode is longer. Is there something missing in the use-package config?

**Comment by DanielGavin** [comment]
Hello

I'm not really sure. I have no experience with emacs.

Maybe @hasanyasin knows something about it. He previously helped someone with emacs configs.

Either way if it works fine, maybe it should be added to the README.md as an additional way to install ols with emacs.

**Comment by DanielGavin** [comment]
Closing it. Feel free to add PR to improve the documentation.
