### ISSUE TITLE
Issues with some inlays inside the parameters of the procedures on the file demo.odin .

### ISSUE THREAD

**Issue by joaocarvalhoopen** [DanielGavin/ols#241]
Following the discussion on the discord of Odin Programming Language.

Please Droaz forget every thing that I told you that was not working I have striped the file of demo.odin to the minimal and it still not working for the majority of the code, but then I did the following and the majority or all the code has comments I will review evry line of the 2500 line of code of the file and come back to you in a momento.
The prroblem was in the ols.json
This those not work with the tilda.

``` json
{
    "$schema": "https://raw.githubusercontent.com/DanielGavin/ols/master/misc/ols.schema.json",
    "collections": [
        { "name": "core", "path": "~/odin/Odin/core" },
        { "name": "shared", "path": "~/odin_proj/demo" }
    ],
    "enable_semantic_tokens": false,
    "enable_document_symbols": true,
    "enable_hover": true,
    "enable_snippets": true,
    "enable_inlay_hints": true
}
```

But work well with this:

``` json
{
    "$schema": "https://raw.githubusercontent.com/DanielGavin/ols/master/misc/ols.schema.json",
    "collections": [
        { "name": "core", "path": "/home/joaocarvalho/odin/Odin/core" },
        { "name": "shared", "path": "/home/joaocarvalho/odin_proj/demo" }
    ],
    "enable_semantic_tokens": false,
    "enable_document_symbols": true,
    "enable_hover": true,
    "enable_snippets": true,
    "enable_inlay_hints": true
}
````

I will see if it works with all procedures inside demo.odin line by line.
defer delete() doesn't work:

line 207    some_map := map[string]int{"A" = 1, "C" = 9, "B" = 4}
line 208    defer delete(some_map)

**Comment by joaocarvalhoopen** [comment]
This one in variadic_procedures() is best described with a screen shot:

![image](https://github.com/DanielGavin/ols/assets/6319988/f735be9c-445f-4d5c-a3f3-4bc1244fb7e2)

**Comment by joaocarvalhoopen** [comment]
In explicit_procedure_overloading() it's is also problematic.

![image](https://github.com/DanielGavin/ols/assets/6319988/2d6798af-16ad-493f-8e2a-4743f9ecd332)

**Comment by joaocarvalhoopen** [comment]
In this case with templates new_entity and the new are also problematic:

![image](https://github.com/DanielGavin/ols/assets/6319988/69d636df-9557-4bc8-8c2e-b7c2bf6738fc)

**Comment by joaocarvalhoopen** [comment]
The last image didn't show the last line:

![image](https://github.com/DanielGavin/ols/assets/6319988/67d5d6a0-ad1a-4a5a-95d2-078eb95a0b7c)

**Comment by joaocarvalhoopen** [comment]
While printing the last field off this fmt.println() it is problematic:


![image](https://github.com/DanielGavin/ols/assets/6319988/270b0fc4-4f7c-440b-b8eb-8c2f4ff4d77d)


While receiving the address to an argument with a  pointer, it is problematic:

![image](https://github.com/DanielGavin/ols/assets/6319988/dc7362e0-3300-4073-a891-d7d0b28c05ad)
 
new() and free() don't show nothing:

![image](https://github.com/DanielGavin/ols/assets/6319988/0803a760-f2d7-4d46-aa01-d97e12e8742a)

**Comment by joaocarvalhoopen** [comment]
alloc() doesn't work correctly:

![image](https://github.com/DanielGavin/ols/assets/6319988/86fbf4b5-6a94-4613-b3f0-8b9f3c56057e)

make(), type_of() , max() don't work correctly,
and so doesn't work this template make_slice()

![image](https://github.com/DanielGavin/ols/assets/6319988/7ef7a8eb-0f6d-4558-9472-284fb6874c1a)

**Comment by joaocarvalhoopen** [comment]
put() doesn't work correctly:

![image](https://github.com/DanielGavin/ols/assets/6319988/4b24358f-4037-4639-9966-1474902024fc)

All this have templates or generics, so they render badly:

![image](https://github.com/DanielGavin/ols/assets/6319988/6644f19b-a6e6-408a-b199-6a5b477338ae)


append() in a vector doesn't work

![image](https://github.com/DanielGavin/ols/assets/6319988/ddae32e5-fb7f-4de6-a7e4-b5ac65efb260)

**Comment by joaocarvalhoopen** [comment]
O thread.pool_init() e o thread.poll_start() nãom funcionam:

![image](https://github.com/DanielGavin/ols/assets/6319988/6cd5d9ac-f6ad-4d41-955e-e589ababe97f)

If it is inside a compile time assert thje size_of() function doesn't show it's inlay:

![image](https://github.com/DanielGavin/ols/assets/6319988/7ed6d4bf-5a96-44a0-914b-293c2dc89c2f)

**Comment by joaocarvalhoopen** [comment]
Inside a Parametric polymorphic checks
in the where of the type the intrinsics.type_is_numeric() doest show but i don't know if this is supposed to show?

![image](https://github.com/DanielGavin/ols/assets/6319988/35675a83-fd5a-4ce9-97bf-da460e4783a3)

**Comment by joaocarvalhoopen** [comment]
In function parameters overloading with generic parameters for the function it doesn't work:

![image](https://github.com/DanielGavin/ols/assets/6319988/febf4fd7-80a4-4c2c-94c0-e3771146b11f)


make() doesn't work:

![image](https://github.com/DanielGavin/ols/assets/6319988/d4791756-460e-48c2-bbd9-8c01ad63f83e)

**Comment by joaocarvalhoopen** [comment]
IMPORTANT:
I correct what I just said, make works because the first parameter is the type!

soa_zip() and soa_unzip() doesn't work:

![image](https://github.com/DanielGavin/ols/assets/6319988/546e7a46-8d44-4161-a6d9-1d6ff4e62e7c)

**Comment by joaocarvalhoopen** [comment]
runtime.default_context()   doesn't work:

![image](https://github.com/DanielGavin/ols/assets/6319988/27e25c88-fa46-4eb8-920b-98886fb11ea6)

big.gcb_lcm() doesn't show correctly:

![image](https://github.com/DanielGavin/ols/assets/6319988/05a55159-4226-4dcd-a2b8-47d385e40c04)

 hadamard_product() for matrixes doesn't show correctly:
 
 
![image](https://github.com/DanielGavin/ols/assets/6319988/67a70bf9-d7a8-4c4a-8c81-65a6e3766249)


And that all the cases inside demo.odin from the Odin language repositorio!

Thank you,

Best regards
João Carvalho

**Comment by joaocarvalhoopen** [comment]
Correction:

runtime.default_context() doesn't have parameters so it is working correctly.

**Comment by DanielGavin** [comment]
Think all of them are fixed. If you still find some not, make one issue each for each problem. It's hard to keep track of all in one issue.
