### ISSUE TITLE
 PROBLEM inferring type of a bitset derived from an enum

### ISSUE THREAD

**Issue by ChuuniMage** [DanielGavin/ols#245]
![image](https://github.com/DanielGavin/ols/assets/28918404/0e48652c-d1d1-4d70-b669-e378c0d6f3c2)

test :: proc () {
	Foo :: enum {
		A,
		B,
		C,
	}
	derived_bit_set := bit_set[Foo]{}
}

**Comment by DanielGavin** [comment]
Fixed.
