### ISSUE TITLE
ols doesn't appear to honor //+private

### ISSUE THREAD

**Issue by deadwanderer** [DanielGavin/ols#246]
Per [the Odin docs on private](https://odin-lang.org/docs/overview/#private):

Using //+private in a file at the package declaration will automatically add @(private) to everything in the file

```
//+private
package foo
```

ols doesn't appear to do this, however. Adding `@(private)` to structs/enums/procs in a file individually does work for ols Intellisense, but the private comment at the top of the file doesn't do anything in the Intellisense (that is, all items in the file are still visible outside the file/package for Intellisense.

**Comment by DanielGavin** [comment]
Should be fixed in https://github.com/DanielGavin/ols/pull/269
