### ISSUE TITLE
Undeclared name 'Auto_Cast' for type 'Field_Flag'

### ISSUE THREAD

**Issue by pedrotrschneider** [DanielGavin/ols#247]
I'm getting a compilation error when trying to build from source:

``` bash
/home/ptrschneider/distrobox/odin/.src/ols/src/server/analysis.odin(711:7) Error: Undeclared name 'Auto_Cast' for type 'Field_Flag'
        if .Auto_Cast in flags {
            ^~~~~~~~^
/home/ptrschneider/distrobox/odin/.src/ols/src/odin/printer/visit.odin(2606:6) Error: Undeclared name 'Auto_Cast' for type 'Field_Flag'
        if .Auto_Cast in flags {
            ^~~~~~~~^
```

Environment:
- OS: Archlinux distrobox inside WSL (Ubuntu 22.04). I know it's an unusual setup, but the error message doesn't seem to be related to the setup.
- odin version `dev-2023-09:2aa3cabd8`, from AUR package `odin-git`

Tried to install the language server both from source, and from the AUR package `odinls`, both gave the same error as a result.

**Comment by DanielGavin** [comment]
There was a new `odin` change recently. It should now work with source.
