### ISSUE TITLE
Issue in OLS in VSCode, with a back tick inside a map  of strings initialization. 

### ISSUE THREAD

**Issue by joaocarvalhoopen** [DanielGavin/ols#248]
Hello,

In the following code, when I compile it compiles correctly, but appears in red with a yellow rectangle surrounding the back tick.
the code is in my repository in the line 166.

https://github.com/joaocarvalhoopen/Odin---Manipulating-the-keyboard-input-and-output-in-Linux/blob/main/linux_dyslexic_help.odin#L166

Visually an image of it is the following, the caret is in the plus "symbol", one line above this line:

![imagem](https://github.com/DanielGavin/ols/assets/6319988/7965d860-1e6e-477c-ae93-d7e4295034d3)

Best regards,
João Carvalho

**Comment by joaocarvalhoopen** [comment]
In the Odin discord, another Odin programmer "laytan" mentioned that it could be:

````Probably not an ols issue, rather an issue with core:odin/parser```

**Comment by DanielGavin** [comment]
Just vscode complaining, nothing to do with `ols`.

Warning from vscode:
```
The character U+00b4 "´" could be confused with the ASCII character U+0060 "`", which is more common in source code. Adjust settings```

**Comment by joaocarvalhoopen** [comment]
Thank you DanielGavin.
