### ISSUE TITLE
Error: 'v' of type '^Range_Stmt' has no field 'reverse'

### ISSUE THREAD

**Issue by sevengiantsstudio** [DanielGavin/ols#249]
I get the following error when installing ols in windows:
./build.bat

ols/src/odin/printer/visit.odin(1312:6) Error: 'v' of type '^Range_Stmt' has no field 'reverse'
        if v.reverse {

**Comment by DanielGavin** [comment]
You are using an old version of Odin. This project is currently built to work with the latest master of Odin.
