### ISSUE TITLE
Cannot build on latest release

### ISSUE THREAD

**Issue by nmsobri** [DanielGavin/ols#252]
When i clone the latest source code and try to build it ( running `./build.bat` ) , i was presented with this error:

`C:/Ols/src/odin/printer/visit.odin(1312:6) Error: 'v' of type '^Range_Stmt' has no field 'reverse'
        if v.reverse {
           ^`

**Comment by DanielGavin** [comment]
You are using an old `odin` version. It currently requires a nightly odin build.
