### ISSUE TITLE
The language server doesn't work on Mac M1

### ISSUE THREAD

**Issue by derpycoder** [DanielGavin/ols#253]
I get this pop-up when I try to open up an odin file:

![image](https://github.com/DanielGavin/ols/assets/25662120/9960ceca-17a1-4ca3-a586-2b7bf18e85a2)

---

So I cloned the repo and tried to build it using `bash build.sh`.

And I got:

```shell
ols-nightly/src/odin/printer/visit.odin(1312:6) Error: 'v' of type '^Range_Stmt' has no field 'reverse'
	if v.reverse {
	   ^
```

Am I using the wrong Odin version?
`odin version dev-2023-08:9453b238`

Or is it something else?

**Comment by DanielGavin** [comment]
You need a newer version of `Odin`. I think there was just a new release that should work.

Yeah right now there is no arm mac runner on github, so I can't make a image just yet.
