### ISSUE TITLE
Disable completing closing parenthesis on autocompleting function

### ISSUE THREAD

**Issue by invrainbow** [DanielGavin/ols#272]
I'm using VSCode with the extension.

It seems when autocompleting a function, it automatically fills in the `()`. This is annoying as I finish typing the parameters and then have to move the cursor past the `)`. In Vim mode this requires me to exit insert mode, move the cursor, and re-enter insert mode.

Is there an option to disable this? I wouldn't mind if the `(` didn't get autocompleted either.

**Comment by DanielGavin** [comment]
Yeah seems reasonable. I'll add a configuration for it.

**Comment by DanielGavin** [comment]
There is now a setting to disable it: "enable_procedure_snippet".

By the way in vscode you can just type `)` when inside the `()`, it will just automatically jump past `)`
