### ISSUE TITLE
ols and odinfmt doesnt' seem to run on some files

### ISSUE THREAD

**Issue by edyu** [DanielGavin/ols#279]
I have a project that has 3 odin files in the same project/directory and ols/odinfmt work on 2 of the 3 files but not the last one. 
The only difference I can tell is that the one that doesn't work is longer than the other 2.
Here are the wc output:
```
  334 erasure/binary_finite_field.odin
  249 erasure/erasure.odin
  370 erasure/finite_field_matrix.odin
  953 total
```
The project is at [here](https://github.com/edyu/odin-erasure). The file that doesn't work is [finite_field_matrix.odin](https://github.com/edyu/odin-erasure/blob/master/erasure/finite_field_matrix.odin). Note that it did work when I started the file so maybe it's because of file size? 

BTW, the way I check whether it works is by adding extra spaces inside a struct and when I write, it should auto shift/reformat the struct.

**Comment by DanielGavin** [comment]
It's normally lack of trailling commas. Right now `core:odin/parser` expects there to commas, where the cpp parser does not care.

If you still have issues reopen it, and I'll look at the file causing issues.
