### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Sampie159** [DanielGavin/ols#284]
I'm on Arch Linux and I have Odin version dev-2023-12 downloaded from the AUR. When I try to build I get these errors: 
![image](https://github.com/DanielGavin/ols/assets/38163547/1aefd2cf-1ffa-42a9-854e-988e346681d2)

**Comment by DanielGavin** [comment]
Old version of Odin. This project supports the latest master. Either download the nighty version or build from source.
