### ISSUE TITLE
Assignments not aligned when using bit_set

### ISSUE THREAD

**Issue by leidegre** [DanielGavin/ols#294]
Incorrect

```odin
rtv_desc := d3d12.DESCRIPTOR_HEAP_DESC {
  Type = .RTV,
  NumDescriptors = BACK_BUFFER_COUNT,
  Flags = {.SHADER_VISIBLE},
}
```

Now without `Flags = {.SHADER_VISIBLE},`

```odin
rtv_desc := d3d12.DESCRIPTOR_HEAP_DESC {
  Type           = .RTV,
  NumDescriptors = BACK_BUFFER_COUNT,
}
```

The consecutive assignments inside the initializer are no longer aligned.

**Comment by leidegre** [comment]
Here's another repo

```odin

Foo :: struct {
	A:     string,
	BBB:   string,
	CCCCC: Bar,
	DD:    Baz,
	EEEE:  int,
}

Bar :: struct {
	A:   string,
	BBB: string,
}

Baz :: bit_set[BazFlag]
BazFlag :: enum {
	A,
	B,
	C,
}

main :: proc() {
	foo := Foo {
		A    = "foo",
		BBB  = "bar",
		EEEE = 42,
	}

	bar := Foo {
		A = "foo",
		BBB = "bar",
		CCCCC = Bar{},
	}

	bar := Foo {
		A = "foo",
		BBB = "bar",
		D = {},
	}
}
```

The alignment of consecutive assignments within the aggregate initializer changes to unaligned when there's a nested bracket of some sort. Is this intentional or unwarranted?

**Comment by DanielGavin** [comment]
The aggregate initializer currently disables alignment, because I'm worried of having to align stuff like this:

```
baz := Foo {
	A = "foo",
	BBB = "bar",
	DD = {
             my_value = 123123
        },
}
```

It's both quite hard to align this correctly. There could even more than just one nest of braces. But in your example there is no named assignments in the aggregate initializer, so it could be possible to have it align anyway for that case.

**Comment by leidegre** [comment]
Yeah, I think it should be consistent. Either align assignments or not but don't change the behavior. 

I've done plenty of compiler work in my days and I could give this a shot.

**Comment by DanielGavin** [comment]
I have now switched it so the bitsets get aligned.
