### ISSUE TITLE
ols fails to build with latest master branch of Odin.

### ISSUE THREAD

**Issue by aleury** [DanielGavin/ols#299]
Hello, I'm new to Odin and was just getting it setup today. When I attempted to build `ols` as described in the readme I encountered this error 

```shell
➜  ols git:(master) ./build.sh
/Users/aeury/ols/src/common/allocator.odin(69:2) Error: Unhandled switch case: Resize_Non_Zeroed
	Suggestion: Was '#partial switch' wanted?
```

It looks the new enum value was added in https://github.com/odin-lang/Odin/pull/3001. I attempted to fix it by adding it to the switch case at `ols/src/common/allocator.odin` and it appeared to at least get the build to pass:

```odin
case .Resize, .Resize_Non_Zeroed
```

**Comment by DanielGavin** [comment]
Should be fixed.
