### ISSUE TITLE
Autocomplete and errors fail on sub-packages

### ISSUE THREAD

**Issue by DreepyYunky** [DanielGavin/ols#304]
Sorry, but why does autocomplete and errors fail when importing a subpackage (a package within another package)

I'm using Neovim and I'm demonstrating this through the Xlib library in X11 and I have at line 12 I set a clearly wrong value but It hasn't given me any errors
<img width="730" alt="Screenshot 2024-02-03 131203" src="https://github.com/DanielGavin/ols/assets/126269099/40bbca18-2b75-4f45-9935-2a5326a923f2">

Maybe this is an error? Some kind of oversight?

**Comment by DanielGavin** [comment]
There is no such package to import. `core:x11/xlib` is not a thing in the core packages.

Can you import packages that are in `core` and complete them, such as `core:fmt`?

**Comment by DreepyYunky** [comment]
You're right, X11 was in `vendor`, not `core`.

It should have given me an error though.

**Comment by DanielGavin** [comment]
I do not control that. I just get the errors from `odin check`, but since that has no line position, I cannot give the error.
