### ISSUE TITLE
No type inference for element when using for in loop

### ISSUE THREAD

**Issue by IllusionMan1212** [DanielGavin/ols#305]
Looping over static arrays, dynamic arrays, slices, maps, and strings using a for in loop doesn't infer the type of the element and its index and causes auto completion and hover to not work

Simple reproducible code
```odin
package main

main :: proc() {
    slice := []int{1, 2, 3, 4, 5}

    for elem in slice {
    }
}
```

**Comment by DanielGavin** [comment]
Fixed in #339
