### ISSUE TITLE
Ols doesn't build with newest Odin

### ISSUE THREAD

**Issue by wilsonk** [DanielGavin/ols#31]
Just a quick note that ols fails to build with Odin as of April 22, 2021 at 21:31 MST.  I reverted back to commit 2db1fe74299766c9a29a33c39299d07e12556bb2 for Odin, rebuilt Odin and then it compiled ols fine.

Just thought I would mention it in case someone else runs into this problem before ols is updated.  :)

**Comment by DanielGavin** [comment]
Thanks for letting me know. I need to make sure to update Odin more often. I'll look at it later today.

**Comment by DanielGavin** [comment]
It has now been updated to support the new Odin version.
