### ISSUE TITLE
Segmentation fault on running `build.sh`

### ISSUE THREAD

**Issue by vaseapinkov** [DanielGavin/ols#318]
### Description
When attempting to build the binaries using the `build.sh` script, the process fails with a segmentation fault error message or a blue screen.

### Error mesage
`./build.sh: line 83: 39686 Segmentation fault: 11  odin build src/ -collection:src=src -out:ols -o:speed $@`

### Observation
After some tinkering around, I found that removing the `-o` flag from the build script allows it to execute without encountering the segmentation fault. Interestingly, I've can built "hello world" apps using the same -o flag with Odin, suggesting that the issue might be specific to this script or my environment.

### Environment
**Odin Version:** dev-2024-03:04f0fbf23
**Operating System:** MacOS 14.2
**Processor:** M1 Pro

I'm a newcomer to low-level languages, and this is my first encounter with a segmentation fault or any memory related problems, but I would love to contribute more into resolving this issue. Any guidance on where to start debugging would be greatly appreciated.

**Comment by DanielGavin** [comment]
Hello. This is an issue with `odin` compiler. There is most likely nothing I can do about that. I have experienced somewhat large programs can have issues with compiling on different optimization modes.

**Comment by vaseapinkov** [comment]
Thanks for the fast response, that was my initial thought as well, it also check with the fact that there are no more issues like this one opened.
I was using `llvm@14` as recommended in the [docs](https://odin-lang.org/docs/install/#requirements). But I just tried to rebuild `odin` using `llvm@17` and the issue is gone, thanks for pointing out on this!
