### ISSUE TITLE
After the new update I get a new error 

### ISSUE THREAD

**Issue by xzores** [DanielGavin/ols#320]
After the new update I get a new error:
```
[Error - 8:58:28 AM] Failed to read/find c:\Users\jakob\AppData\Roaming\Code\User\globalStorage\danielgavin.ols\147110303/ols.json
D:/a/ols/ols/src/common/fuzzy.odin(193:2) runtime assertion
[Info  - 8:58:28 AM] Connection to server got closed. Server will restart.
true
```

**Comment by Hyrtwol** [comment]
I had same error the other day, fixed it for now by creating an empty ols.json file at the location. ols must have trouble detecting if the file exists.

**Comment by Hyrtwol** [comment]
Oh and ofc it's now missing again after an update, not ideal :p

**Comment by DanielGavin** [comment]
@Hyrtwol Whether the global file exists or not, should not have any affect on anything, except that it won't use it then. I could stop writing out the error, but it's better to show where it tried to look. 

Are you saying something doesn't work if the global file doesn't exist? I would expect more people to have complained about it. Must people don't even know about the global config.

**Comment by DanielGavin** [comment]
This is related to https://github.com/DanielGavin/ols/issues/316

**Comment by DanielGavin** [comment]
Fixed in #316

**Comment by Hyrtwol** [comment]
sry for the late reply, the missing global ols.json don't cause any issues. maybe nice if it could be a warning instead

**Comment by DanielGavin** [comment]
@Hyrtwol Yeah most likely should be. Technically all the of ols.json missing are technically not errors.
