### ISSUE TITLE
Unknown library collection: 'base'

### ISSUE THREAD

**Issue by jakelacey2012** [DanielGavin/ols#321]
I get the following error in macOS Ventura, after cloning and running `./build.sh`. Is there any additional information I get give that would be helpful to fix the issue?

```
Unknown library collection: 'base'
```

**Comment by jakelacey2012** [comment]
So it looks like updating (re-cloning and re-building) odin allows the build.sh to run without this error, don't know if it works yet though.

**Comment by DanielGavin** [comment]
`base` is a new collection for odin compiler. That usually just means that you are running an old Odin version.
