### ISSUE TITLE
"Go to definition" on platform-specific symbols doesn't select the current OS

### ISSUE THREAD

**Issue by jakubtomsu** [DanielGavin/ols#327]
When I try to use "go to definition" on procedures which are implemented in multiple platform specific files (like in `core:os` or `core:sync`) it doesn't take me to the implementation for the current OS (in my case Windows) but to the OpenBSD variant for some reason.

Also, I believe Vscode can show a pop up with multiple "go to definition" files to let the user select which one they need. Maybe OLS could use that instead somehow?

**Comment by DanielGavin** [comment]
Should be fixed. It's because I haven't added OpenBSD, so it just assumed it was a normal file.
