### ISSUE TITLE
Option to autocomplete procedures without parenthesis

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#334]
Currently when auto-completing procedure names, OLS will add parenthesis at the end of the proc name, and place the cursor between the parenthesis.
Could this perhaps be disabled with an option?
This might be a weird request as the feature seems very handy.
I'm just used to LSPs not doing that, so I have opposite habits.
It's not that big of a deal though.
But maybe others have similar experiences.

**Comment by DanielGavin** [comment]
`enable_procedure_snippet` should be able to disable it.

**Comment by thetarnav** [comment]
indeed :smile: 
I'll add it to the schema.
