### ISSUE TITLE
The VSCode extension cannot find Odin in my path.

### ISSUE THREAD

**Issue by Jankoy** [DanielGavin/ols#350]
I do in fact have Odin in my path, but the extension refuses to acknowledge this and keeps giving me this error and only working with some functionality.
```
Odin cannot be found in your path environment. Please install Odin or add it into your path environment before going any further.
```
This is what I have in my `~/.bashrc` file:
```bash
export ODIN_ROOT="$HOME/builds/Odin"
export PATH="$ODIN_ROOT:$PATH"
```
Anybody know what's up?

**Comment by laytan** [comment]
VSCode is probably not loading/using your bashrc, see: https://stackoverflow.com/questions/51820921/vscode-integrated-terminal-doesnt-load-bashrc-or-bash-profile

**Comment by Jankoy** [comment]
I tried the `odin_command` field, but it made no difference, I still got the error and most functions remained broken. The article you linked has given me some insight, it seems the environment is setup properly when I use the command to start VSCode, but the field for setting a login shell with `-l` doesn't seem to do anything. I feel a little silly for not realizing I should have googled about VSCode generally and not this plugin specifically. If I can completely solve the issue I will post a comment and close this issue. Thank you for your help!

**Comment by Jankoy** [comment]
Hmm, I think I made it worse somehow.
```
 *  Executing task: odin build . -debug 

/bin/bash: line 1: odin: command not found

 *  The terminal process "/bin/bash '-l', '-c', 'odin build . -debug'" failed to launch (exit code: 127). 
 *  Terminal will be reused by tasks, press any key to close it.
```
I changed a couple settings and now even running it from a shell doesn't work anymore. Also the integrated terminal has env, just not the extensions and launch profiles. This is very confusing.

**Comment by geajack** [comment]
This issue really shouldn't be closed - I shouldn't have to go messing with bash config files to get a VSCode extension working. I realize the extension needs to know how to find Odin somehow, but that should just be an extension setting, and this error popup should tell you which setting to set.

**Comment by Filip-Anicic** [comment]
I tried @jack-jjm suggestion, but still the same issue of the ols server not finding the compiler
```bash
bash-5.2$ echo $PATH
/home/filip/Development/Odin:/home/filip/.local/bin:/home/filip/bin:/app/bin:/app/bin:/app/bin:/usr/bin:/home/filip/.var/app/com.vscodium.codium-insiders/data/node/bin:/home/filip/.var/app/com.vscodium.codium-insiders/data/cargo/bin:/home/filip/.var/app/com.vscodium.codium-insiders/data/python/bin:/home/filip/.var/app/com.vscodium.codium-insiders/data/gem/ruby/3.3.0/bin
bash-5.2$ echo $ODIN_ROOT
/home/filip/Development/Odin
```

I also made a symbolic link, which I later renamed, after adding the build folder to the PATH as well. No changes
```bash
which odin
~/Development/Odin/odin

which odin-wasd
~/bin/odin-wasd
```
