### ISSUE TITLE
ols times out when incorrectly specifying array type (e.g. `int[]` instead of `[]int`)

### ISSUE THREAD

**Issue by kapoko** [DanielGavin/ols#370]
When incorrectly specifying an array type `ols` times out.

```odin
test_proc :: proc(arg: int[]) {}
```

## Expected behaviour

Compiler gives the following output:
```
test_proc :: proc(arg: int[]) {
                       ^~~~^
Suggestion: Did you mean '[]int'?
```

Instead I get `timeout` from ols (when formatting). 

Thanks for the great software!

**Comment by DanielGavin** [comment]
Fixed.
