### ISSUE TITLE
Missing support for assignment completion for unions of enums

### ISSUE THREAD

**Issue by mtarik34b** [DanielGavin/ols#372]
Assignment completion for unions of enums seem currently not supported:
![image](https://github.com/DanielGavin/ols/assets/131314797/65dd9ba6-9c3b-420e-b588-37e746d8ec2c)
```odin
package pkg

import "core:fmt"

Subenum1 :: enum { ONE }
Subenum2 :: enum { TWO }
Superenum :: union { Subenum1, Subenum2 }
fn :: proc(mode: Superenum) { fmt.println(mode) }

main :: proc() {
	fn(.)
}
```

**Comment by DanielGavin** [comment]
Added support for it on the rename branch. Will close this issue when it's merged to master.

**Comment by DanielGavin** [comment]
Merged
