### ISSUE TITLE
Parse statements with `or_continue` and `or_break`

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#382]
It seems that `or_else` and `or_return` are supported, but not `or_continue` and `or_break`.
(no semantic tokens/go to definition/hover)
Which is understandable as they were added recently.
I'm guessing it should be a simple change to parse them.

**Comment by DanielGavin** [comment]
Are we talking about the formatter?

**Comment by thetarnav** [comment]
no, about ols, is it really not in ast?
From looking at the ast package there is `Or_Branch_Expr` node and `Token_Kind.Or_Break` and `Token_Kind.Or_Continue`

**Comment by DanielGavin** [comment]
It seems it is. Fixed.
