### ISSUE TITLE
Unable to find x library.

### ISSUE THREAD

**Issue by GiorgosAthanasopoulos** [DanielGavin/ols#388]
Hello,
Thank you very much for developing this.

Although on linux everything works find, damn windows as always has a problem with core/base/vendor libraries not in the ols "workspace" leading to `unable to find x type` type of messages when i try to jump to their definition.

Some info on my setup:
Windows 11, Sublime text 4
Installed st4 lsp plugin, ols installed and in path, odin installed and in path, ODIN_ROOT set to odin root installation folder, LSP.sublime-settings filled with default settings, as well as default odinfmt.json and ols.json in project root. I have also tried adding the vendor/core libraries to the collections array in the ols.json but that doesnt seem to help much.

I havent seen a similar issue so I would appreciate some help with this.
Thank you, 
George.

**Comment by DanielGavin** [comment]
What version of Odin are you using. Is it the latest?
