### ISSUE TITLE
Constant timeouts

### ISSUE THREAD

**Issue by sudokit** [DanielGavin/ols#389]
Not sure if its related to helix (editor I am using), but ols seems to constantly time out. Not sure why. Ill add some logs:
[log is humongous, enabled really verboselogging](https://0x0.st/XPmN.txt)

**Comment by DanielGavin** [comment]
Is there a simple repro that causes the timeout? Have you tried other editors, and do they cause the same issue? Helix is not the most stable editor currently with LSP.

**Comment by sudokit** [comment]
Yeah no as I mentioned I was unable to find any way to reproduce the timeout. Ill be on the lookout. Nop I havent really tried other other editors. I increased the timeout so hopefully that helps

**Comment by sudokit** [comment]
happened as well today with vscode with the error:
```
/home/sudokit/langs/ols/src/common/position.odin(152:31) Invalid slice indices -1:1885 is out of range 0..<1885
```

**Comment by DanielGavin** [comment]
Maybe it's some partial ast that gives some bad node. I'll add a `max()`. That should fix the issue with that crash. I'd rather return some wrong position then crash.

**Comment by DanielGavin** [comment]
Fixed. It'll instead print an error if the token range is invalid.

**Comment by DanielGavin** [comment]
Closing issue. Make a new issue if you find more errors.

**Comment by sudokit** [comment]
Thank you! 
Errors, I think, are better than a crash, since a lsp restart isn't needed. 
What I think then happens in my case is that the lsp restarts but its still out of range and instantly crashes.

**Comment by sudokit** [comment]
Hehehe... sorry similar error so same issue...
```/home/sudokit/langs/ols/src/server/analysis.odin(159:31) Index 60 is out of range 0..<60```
how about a upper limit as well ,p

**Comment by DanielGavin** [comment]
Has nothing to do with the previous error. I should have fixed it thought.
