### ISSUE TITLE
OLS timesout on format

### ISSUE THREAD

**Issue by romero-kenny** [DanielGavin/ols#392]
My OLS head: 49a6347 and Odin head: 45d506602
## Error from LspLog
[ERROR][2024-05-25 16:23:20] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/kenny/.local/share/nvim/mason/bin/ols"	"stderr"	'/Users/kenny/.local/share/nvim/mason/bin/ols_fldr/src/odin/printer/visit.odin(2949:3) panic: unhandled get_node_length case &Comp_Lit{node = Expr{expr_base = Node{pos = Pos{file = "/Users/kenny/code_space/advent_of_code/odin_advent/2015_advent/src/day_three.odin", offset = 1352, line = 62, column = 3}, end = Pos{file = "/Users/kenny/code_space/advent_of_code/odin_advent/2015_advent/src/day_three.odin", offset = 1358, line = 62, column = 9}, state_flags = Node_State_Flags{}, derived = 0x138489548}, derived_expr = 0x138489548}, type = <nil>, open = Pos{file = "/Users/kenny/code_space/advent_of_code/odin_advent/2015_advent/src/day_three.odin", offset = 1352, line = 62, column = 3}, elems = [0x138489398, 0x138489490], close = Pos{file = "/Users/kenny/code_space/advent_of_code/odin_advent/2015_advent/src/day_three.odin", offset = 1357, line = 62, column = 8}, tag = <nil>}\n'
[ERROR][2024-05-25 16:24:24] ...lsp/handlers.lua:623	"Failed to unmarshal check results: Invalid_Data"
[ERROR][2024-05-25 16:24:30] ...lsp/handlers.lua:623	"Failed to unmarshal check results: Invalid_Data"
[ERROR][2024-05-25 16:24:33] ...lsp/handlers.lua:623	"Failed to unmarshal check results: Invalid_Data"
[ERROR][2024-05-25 16:27:16] .../vim/lsp/rpc.lua:770	"rpc"	"/Users/kenny/.local/share/nvim/mason/bin/ols"	"stderr"	"/Users/kenny/.local/share/nvim/mason/bin/ols_fldr/src/odin/printer/visit.odin(2949:3) panic"

## Code that times it out
Code compiles and correct output is achieved, but just crashes OLS.
```
	visited_house := map[HousePosition]int {
		{0, 0} = 2,
	}
```

## Weird behaviour if formated after the code is deleted, then undone but formatted again

I am using kickstart.nvim and did not change much of the Lsp config, incase it might be that.

https://github.com/DanielGavin/ols/assets/102318018/04a3f8e1-c9ef-4009-a251-60c1a19ce781

**Comment by DanielGavin** [comment]
Should be fixed.
