### ISSUE TITLE
New directive #hash isn't properly parsed by OLS

### ISSUE THREAD

**Issue by dmitsuki** [DanielGavin/ols#393]
Using the new `#hash("string" "hash")` doesn't properly parse with ols. Ols reports back a syntax error.

**Comment by DanielGavin** [comment]
It's an issue with `core:odin/parser`

**Comment by laytan** [comment]
Fixed: https://github.com/odin-lang/Odin/commit/27f9f0ba171444f48021744af2792bbfa290407b
