### ISSUE TITLE
OLS Build Failed

### ISSUE THREAD

**Issue by Frawing** [DanielGavin/ols#397]
Odin version: dev-2024-04a

./build.sh 
/home/gfrawing/Desktop/odin_build/OLS/src/odin/printer/visit.odin(292:45) Error: Cannot assign value 'path' of type 'string' to '^Expr' in procedure argument
	document = cons(document, visit_expr(p, path))
	                                        ^~~^
/home/gfrawing/Desktop/odin_build/OLS/src/odin/printer/visit.odin(299:54) Error: Cannot assign value 'v.fullpaths[0]' of type 'string' to '^Expr' in procedure argument
	... expr(p, v.fullpaths[0])) ...

**Comment by DanielGavin** [comment]
You need the latest source version of Odin. There was a change recently(a week ago).
