### ISSUE TITLE
`foreign import` library path corrupted after code format

### ISSUE THREAD

**Issue by ccll** [DanielGavin/ols#399]
After OLS in VSCode updated automatically to latest nightly (20224-06-03), when Odin files were saved and auto formated, the `foreign import ...` statements will be corrupted.

The original file:
```odin
when ODIN_DEBUG {
	foreign import uv "../../vcpkg/installed/x64-linux/debug/lib/libuv.a"
} else {
	foreign import uv "../../vcpkg/installed/x64-linux/lib/libuv.a"
}
foreign import uv_wrapper "../../build/lib/uv_wrapper.a"
```

After format:
```odin
when ODIN_DEBUG {
	foreign import uv foreign
} else {
	foreign import uv foreign
}
foreign import uv_wrapper foreign
```

I like OLS a lot, the intellisense and format are very fast and accurate, but the nightly release scheme is a bit frightening. I'm wondering if it can be released under a semantic versioning scheme, allowing user to pin-point a version they prefer in VSCode settings.

**Comment by DanielGavin** [comment]
Yeah it was caused by a change in `core:odin/parser`. It is more by fault that my format tests actually failed, but for some reason it doesn't fail the nightly build. It should have been caught. Regarding semantic versioning, it sounds like a good idea, but not sure if I have time to add it now.

**Comment by DanielGavin** [comment]
Is now fixed in the latest odin version. I'll rebuild the nightly now.

**Comment by ccll** [comment]
Totally understood. Thanks for your great work despite limited time. ❤️
