### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by naomipappe** [DanielGavin/ols#400]
Cloning and executing Windows build script, I get
```
$ ./build.bat
E:/ols/src/odin/printer/visit.odin(292:45) Error: Cannot assign value 'path' of type 'string' to '^Expr' in procedure argument 
        document = cons(document, visit_expr(p, path)) 
                                                ^~~^
E:/ols/src/odin/printer/visit.odin(299:54) Error: Cannot assign value 'v.fullpaths[0]' of type 'string' to '^Expr' in procedure argument
        ... expr(p, v.fullpaths[0])) ...
```
This is reproduced on commit `b3ed829bd3623748a34b9031e27e8c693a226232` on `master` branch.

**Comment by DanielGavin** [comment]
You need a later version. There was a change in `core:odin/ast` recently.

**Comment by naomipappe** [comment]
Thanks! I just started with Odin and forgot that it is actively worked on. 

Thank you for your work on the language server!
