### ISSUE TITLE
Crash on shadowing proc name in it's body

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#403]
There is a bug that crashes the server
basically if you shadow declaration names
like here:
```odin
main :: proc () {
	main := m // completion code will cause crash when typing here
}
```
the ident has an offset of -1 which causes a bounds check failure
```
[Trace - 9:11:10 PM] Sending request 'textDocument/completion - (1)'.
[Trace - 9:11:10 PM] Sending request 'textDocument/documentSymbol - (2)'.
[Trace - 9:11:10 PM] Sending request 'textDocument/documentLink - (3)'.
/home/thetarnav/ols/src/common/position.odin(157:31) Invalid slice indices -1:382 is out of range 0..<382
```
happens on both `master` and `rename` branches

![Screenshot from 2024-06-12 21-27-36](https://github.com/DanielGavin/ols/assets/24491503/88e0a896-ca9e-4361-8895-a49a4ca257af)

Interestingly the `offset < 0` check is not hit, so it's reassigned to `-1` after second `go_backwards_to_endline` call.

**Comment by DanielGavin** [comment]
Doesn't happen to me on the rename branch.

**Comment by thetarnav** [comment]
Just pulled and rebuilt and the same thing.

[Screencast from 14.06.2024 18:34:40.webm](https://github.com/DanielGavin/ols/assets/24491503/eea3be9b-48ea-4098-bd51-5e3c41278506)

**Comment by DanielGavin** [comment]
I see it now. I was running on the release ols without bounds check. I guess you are running on the debug build?

**Comment by DanielGavin** [comment]
Should be fixed on rename.

**Comment by thetarnav** [comment]
I'm just doing `./build.sh`. it doesn't disable bounds checks. Only `./build.bat` does.
And it doesn't happen anymore :+1:

**Comment by DanielGavin** [comment]
merged to master.
