### ISSUE TITLE
OLS confused by bit field definitions

### ISSUE THREAD

**Issue by dogue** [DanielGavin/ols#409]
Minor bug and does not interfere with usage of Odin or OLS.

I'm getting an error in the editor `you cannot use a block statement in the file scope` when defining `bit_field` types.

Running `odin check . -no-entry-point -warnings-as-errors -strict-style -vet` (as strict as I could make it) passes with no errors. Building the project also succeeds without error.

![image](https://github.com/DanielGavin/ols/assets/16505662/0a38ad53-d60b-4384-863a-d1e3695c9e22)

Edit: According to Mason this is on the nightly release.

![image](https://github.com/DanielGavin/ols/assets/16505662/242fe77d-d44e-4844-9260-af6de3c4dbec)

**Comment by DanielGavin** [comment]
You might have used an old version of Odin and Ols. I can't reproduce it.
