### ISSUE TITLE
Put shorter variable attributes on one line with the attribute target

### ISSUE THREAD

**Issue by redpenguinyt** [DanielGavin/ols#415]
Currently, ols formats `@static x := 3` to:
```odin
@(static)
x := 3
```
which, for such a short decorator, is unnecessary. ols should (by default, or as an option) format attributes to appear on the same line as their target, as well as dropping parenthesis when no arguments are passed (as shown in the https://odin-lang.org/docs/overview/#private example)

**Comment by DanielGavin** [comment]
Yes that should be the default.

**Comment by redpenguinyt** [comment]
i think there should be an option for ols to instead format it as:
```odin
@static x := 3
```

**Comment by DanielGavin** [comment]
Maybe you misunderstood me. The default should be `@static x := 3` for variables with no other attributes in the variables.

**Comment by redpenguinyt** [comment]
ah you meant should be as in should be implemented? i see, i was a bit confused by the wording

**Comment by DanielGavin** [comment]
Fixed. It should now be able to be one lined.
