### ISSUE TITLE
Add support for `raw_data` macro

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#417]
The `raw_data` macro is too complicated to be added to `builtin.odin` probably.
So it needs to be hard coded, but it would be nice to have a autocomplete and hover information about it and the returned types.
in odin code its something like this:
```odin
raw_data_string  :: proc (v: string)         -> [^]u8                           ---
raw_data_slice   :: proc (v: $T/[]$E)        -> [^]E                            ---
raw_data_dynamic :: proc (v: $T/[dynamic]$E) -> [^]E                            ---
raw_data_array   :: proc (v: ^$T)            -> [^]intrinsics.type_elem_type(T) ---
```

**Comment by thetarnav** [comment]
actually nevermind
I think it can be added to builtin
will try to do that

**Comment by thetarnav** [comment]
nope
https://github.com/odin-lang/Odin/pull/3835

**Comment by DanielGavin** [comment]
He might not want the procedures you made, but we still need completion for it. I agree if the procedures we make don't reflect what happens in the compiler, it's a problem.

**Comment by thetarnav** [comment]
Yeah I guess I could still add it to ols’s builtin file, since it’s just for completions. I’ll see how that works
