### ISSUE TITLE
Negative character_width shoud disable it

### ISSUE THREAD

**Issue by RichardFevrier** [DanielGavin/ols#419]
`character_width: -1` shoud disable this specific formatting
Amazing project btw ❤️

**Comment by DanielGavin** [comment]
Don't quite follow. That is an invalid value. If anything the formatter should either ignore it and use the default value, or not even format anything. 

If you want everything one lined you can pick an high value.

**Comment by RichardFevrier** [comment]
> That is an invalid value

Alright, then integrate this behavior and it becomes a valid value! Magic isn't it?
