### ISSUE TITLE
ols runtime assertion crash in analysis.odin:158:2 

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#421]
to replicate:

```odin
package bug

Rect :: struct {y: f32}

rect_empty :: Rect{}

foo :: proc (r: Rect, y: f32) -> (res: Rect) {
	res = r
	res.y += y
	return
}
```

then remove `struct {y: f32}` from the third line, leaving only `Rect :: `

it doesn't crash when you have `Rect :: ` from the start after restart

here is the assert that fails:

![Screenshot from 2024-07-04 13-28-45](https://github.com/DanielGavin/ols/assets/24491503/ab71bacb-477d-4c79-bace-e4d66c793432)

in `internal_resolve_type_expression` for the `res.y` selector node

**Comment by DanielGavin** [comment]
Should be fixed in rename.
