### ISSUE TITLE
Doom Emacs configuration - I'm totally confused now.

### ISSUE THREAD

**Issue by XenoBenn** [DanielGavin/ols#429]
So I read these issues: [#239](https://github.com/DanielGavin/ols/issues/239) [#237](https://github.com/DanielGavin/ols/issues/237) and also [this](https://discourse.doomemacs.org/t/set-up-lsp-mode-or-eglot-for-insert-language-here/62)

But now I'm totally confused and I think I switched on a lot of things that shouldn't be open.

If someone has a Doom Emacs and has set up the ols, I would appriciate some help.

Platform: Windows 10

Here's what I already did, and works.

- [x] Odin-mode installed through .doom.d/packages.el
- [x] OLS was built on Windows and in PATH

Here are my code snippets and and the files, that I made changes for this to work.

On my .doom.d/init.el I have this:
```;; Adding Odin LSP

load (expand-file-name "~/.local/odin-mode/odin-mode.el")

;; With odin-mode (https://github.com/mattt-b/odin-mode) and lsp-mode already added to your init.el of course!.
(setq-default lsp-auto-guess-root t) ;; if you work with Projectile/project.el this will help find the ols.json file.
(defvar lsp-language-id-configuration '((odin-mode . "odin")))
(lsp-register-client
 (make-lsp-client :new-connection (lsp-stdio-connection "c:/ols/")
                  :major-modes '(odin-mode)
                  :server-id 'ols
                  :multi-root t)) ;; This is just so lsp-mode sends the "workspaceFolders" param to the server.
(add-hook 'odin-mode-hook #'lsp)

```
(This code sometime crashes my Emacs)

On my .doom.d/packages.el This:
```(package! odin-mode
  :recipe (:host github :repo "mattt-b/odin-mode"
                 :files ("odin-mode.el")))

(use-package eglot
  :ensure t
  :config
  (add-to-list 'eglot-server-programs '(odin-mode . ("ols")))
  :hook
  ((odin-mode . eglot-ensure))
  )
```

This is the things so far I have changed to have LSP working.

Doom doctor gives me this:

>   x There was an unexpected runtime error
    Message: Symbol's value as variable is void
    Details: (load)
    Backtrace:
      (load-with-code-conversion "c:/Users/Beni/.doom.d/config.el" "c:/Users...
      (load "~/.doom.d/config" nil nomessage)
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (...
      (doom-load "~/.doom.d/config")
      (let ((doom-module-context [1 105 -105 :user nil nil nil])) (doom-load...
      (let ((old-custom-file custom-file)) (let ((doom-module-context [2 -11...
      (let ((doom-context doom-context)) (let ((tail (ensure-list 'modules))...
      (if (or (doom-context-p 'init) (doom-context-p 'reload)) (let ((doom-c...
      (load-with-code-conversion "c:/Users/Beni/.emacs.d/.local/etc/@/init.2...
      (load "c:/Users/Beni/.emacs.d/.local/etc/@/init.29.el" noerror nomessage)
      (condition-case e (load path noerror 'nomessage) ((debug doom-error) (...
      (doom-load "c:/Users/Beni/.emacs.d/.local/etc/@/init.29.el" noerror)
GNU Emacs     v29.3            nil
Doom core     v3.0.0-pre       grafted, HEAD -> master, origin/master, origin/HEAD a99c6b9 2024-06-23 17:15:51 -0400
Doom modules  v24.07.0-pre     grafted, HEAD -> master, origin/master, origin/HEAD a99c6b9 2024-06-23 17:15:51 -0400

I don't know what to change in init.el but there are a lot of things for LSP control, and honestly I don't understand 90% of the packages there.

If I try to open it with eglot it says "Couldn't guess LSP server"

Also on the root of the workspace, I added an ols.json with the contenct of this:
```{
    "$schema": "https://raw.githubusercontent.com/DanielGavin/ols/master/misc/ols.schema.json",
    "collections": [
        { "name": "odin", "path": "e:/repos/odin" }
    ],
    "enable_semantic_tokens": false,
    "enable_document_symbols": true,
    "enable_hover": true,
    "enable_snippets": true,
    "profile": "default",
    "profiles": [
        { "name": "default", "checker_path": ["src"]},
        { "name": "linux_profile", "os": "linux", "checker_path": ["src/main.odin"]},
        { "name": "windows_profile", "os": "windows", "checker_path": ["src"]}
    ]
}
```

I hope this information is helpful for someone to understand what is my problem. Thanks

**Comment by DanielGavin** [comment]
If you haven't solved it yet, try the Odin discord ols channel. You'll probably have better help there.
