### ISSUE TITLE
Error squiggles with #load_hash despite compiling and running.

### ISSUE THREAD

**Issue by Chamberlain91** [DanielGavin/ols#431]
I think OLS is unaware of `#load_hash(path, type)`, or at least how I've tried to use it.

Overview shows it existing, and the code compiles, but the language plugin complains anyway.
https://odin-lang.org/docs/overview/#load_hashstring-path-string-hash

![image](https://github.com/user-attachments/assets/f180efe6-9a36-4449-a478-64e8f546ce29)

![image](https://github.com/user-attachments/assets/de35163b-9b76-4601-8724-063a0958085c)

**Comment by Chamberlain91** [comment]
Might be related to https://github.com/DanielGavin/ols/issues/363

**Comment by DanielGavin** [comment]
Needs to be fixed in `core:odin/parser`

**Comment by laytan** [comment]
Fixed: https://github.com/odin-lang/Odin/commit/27f9f0ba171444f48021744af2792bbfa290407b
