### ISSUE TITLE
Error: 'v' of type '^Import_Decl' has no field 'attributes' 

### ISSUE THREAD

**Issue by CertNZone** [DanielGavin/ols#432]
When attempting to build OLS with the "./build.sh" command I get the following error. 
![image](https://github.com/user-attachments/assets/e646d0dc-b836-40a0-8fee-8629c53ec4f1)

This appears to be a compile error. 

I attempted to find the source of the problem in the code but was unable to intuit from the surrounding code block where the error is originating. 
```	
case ^Import_Decl:
		document := move_line(p, decl.pos)

		if len(v.attributes) > 0 {
			document = cons(
				document,
				visit_attributes(p, &v.attributes, v.pos),
```

**Comment by DanielGavin** [comment]
There is no issue. You just have an old odin version.
