### ISSUE TITLE
Problem Analyzing Certain Variables

### ISSUE THREAD

**Issue by dozn** [DanielGavin/ols#437]
Doesn't detect `i` here (can't tell you the type or rename it):
```f#
package main

main :: proc() {
    i := int(5)
}
```
same with `rune_` here, although it works just fine if you iterate over a `[]int` instead:
```f#
package main

main :: proc() {
    for rune_ in "test" {}
}
```

**Comment by DanielGavin** [comment]
Fixed both problems.
