### ISSUE TITLE
False positive on multi-line procedure return values

### ISSUE THREAD

**Issue by vicvi1997** [DanielGavin/ols#447]
This is valid Odin that compiles and run OK:
![odin1](https://github.com/user-attachments/assets/b8cb99bb-1590-4cec-8adc-b6bfc594270b)
but as you can see, OLS is throwing 3 false positives with messages:
- expected ')' after parameter list, got 'newline'
- expected a statement, got )
- expected a statement, got }

If I put the return values in one line like this:
![odin2](https://github.com/user-attachments/assets/cde146fd-24fc-4cdc-a0fe-1eac76758e8a)
the false positives disappear.

The issue should be straightforward to reproduce, let me know if you need further information from my side.

Odin version: dev-2024-07:65c91b7dd
Text Editor: VSCode
OLS extension version: v0.1.30

**Comment by vicvi1997** [comment]
The issue might be caused by the formatter that tries to enforce the declaration of the procedure in 1 line. I think it would be a great addition to be able to split each parameter of a procedure and each return value into different lines for better readability. Maybe add this as an optional setting?

**Comment by vicvi1997** [comment]
After resolving all the false positives, OLS formatted the code above like this:
![odin3](https://github.com/user-attachments/assets/6a66644a-6bc5-49ec-919d-b18039ca5561)

**Comment by thetarnav** [comment]
If lsp reports errors with "(Syntax)" detail, but you don't see them when compiling, then it is probably a `core:odin/parser` package issue, so better to report it in Odin repo since it has to be fixed there.

**Comment by vicvi1997** [comment]
@thetarnav I will do that, thanks. But regarding how OLS formats the code, would it be possible to add a setting that allowed declaring procedures in multiple lines (see image 1) instead of enforcing the declaration in just 1 line (see image 3) ?

**Comment by DanielGavin** [comment]
There is no way of enforcing multiple lines. There is no plan to add a config for it. Technically you can force it by adding a comment.
