### ISSUE TITLE
macos build crash

### ISSUE THREAD

**Issue by SrUmut** [DanielGavin/ols#450]
I am using a ARM Macos machine, when I run the build.sh I get the following error:

/Users/srumut/ols/src/server/unmarshal.odin(36:36) Error: 'variant' of type 'Type_Info_Struct' has no field 'field_count' 
	for field, i in variant.names[0:variant.field_count] { 
	                                ^~~~~~^ 
/Users/srumut/ols/src/server/marshal.odin(422:31) Error: 'info' of type 'Type_Info_Struct' has no field 'field_count' 
	for name, i in info.names[0:info.field_count] { 
	                            ^~~^

**Comment by DanielGavin** [comment]
Hey

You are using an old Odin version. Try the nightly build of Odin or build it from source.
