### ISSUE TITLE
Linux, no compile, no joy.

### ISSUE THREAD

**Issue by bmildh** [DanielGavin/ols#451]
I get the same issue that these two had: issue [433](https://github.com/DanielGavin/ols/issues/433), [436](https://github.com/DanielGavin/ols/issues/436).

```
Error: 'variant' of type 'Type_Info_Struct' has no field 'field_count' 
        for field, i in variant.names[0:variant.field_count] { 
```
odin report:

```
Odin:    dev-2024-07:861ad2037
        OS:      Arch Linux, Linux 6.10.1-arch1-1
        CPU:     AMD Ryzen 5 5600G with Radeon Graphics         
        RAM:     31457 MiB
        Backend: LLVM 18.1.8
```
Best regards.

**Comment by DanielGavin** [comment]
Hey

You have an old Odin version. You either need to compile Odin from source, or pick the nightly version.

**Comment by bmildh** [comment]
Ah, yes. I thought I'd updated earlier today, but most not have done so.  :flushed:
