### ISSUE TITLE
No signature for resolved procedure groups

### ISSUE THREAD

**Issue by thetarnav** [DanielGavin/ols#462]
```odin
add_num :: proc (a, b: int) -> int {return a + b}
add_vec :: proc (a, b: [2]f32) -> [2]f32 {return a + b}
add     :: proc {add_num, add_vec}

main :: proc() {
	foo := add(2, 10) // `foo` doesn't show up anything
	bar := add(2, )   // `bar` shows up `int`
}
```

type of `foo` is not getting resolved and `add` has a generic `proc` signature, instead `proc (a, b: int) -> int` of the procedure getting resolved.

![image](https://github.com/user-attachments/assets/0a4f4e8b-d382-4c3c-8e0b-5288ef1d13b4)

But when typing the paramenters, the correct signature apprears.

![image](https://github.com/user-attachments/assets/669b9058-60f4-48ad-9ffc-85cc9b654ae7)

This affects also `make`, where we don't get to see the inlay hints for default arguments, as we can with `new`.

![image](https://github.com/user-attachments/assets/d6b27e3e-f013-44db-baec-3071c9711514)

![image](https://github.com/user-attachments/assets/b83c1ee0-5adc-4158-8840-0bea9596d486)

**Comment by DanielGavin** [comment]
All issues should be fixed.
