### ISSUE TITLE
Issue with return types in nested procedures.

### ISSUE THREAD

**Issue by Chamberlain91** [DanielGavin/ols#468]
I've noticed an issue with internal / nested procedures not being served properly.

Replication below:
```
package bug

import "core:fmt"

Example :: struct {
	score: int,
}

main :: proc() {

	val := internal_helper()
	fmt.println(val)

	internal_helper :: proc() -> Example {
		return {score = 0}
	}
}
```

Here `val` has no type in when I mouse over, nor does it autocomplete. I would expect it can resolve `Example` and autocomplete `.score` as if it were at the normal global level.

**Comment by DanielGavin** [comment]
Yeah it seems like it works if `val := ...` is after declaring the `internal_helper`. So most likely an issue with not handling the locals as they were global locals.

**Comment by DanielGavin** [comment]
Fixed.
