### ISSUE TITLE
Unhelpful completion after colon in switch cases

### ISSUE THREAD

**Issue by differenceclouds** [DanielGavin/ols#478]
Unsure if this is an ols issue. If not, no problem, guidance welcome. I'm using Sublime Text.

Basically, after typing a colon in a switch case, there are a bunch of things that don't make sense in the autocomplete. I think there should be zero auto-complete in this case, just allowing spaces, tabs, and line returns without any autocomplete coming up until you start typing something. But instead, I have to hit escape every time, or more likely, make a mistake, delete it and try again.

This is one of just a couple places that make me want to disable autocomplete altogether, but if it is able to be controlled, there is no need.

![Screen Shot 2024-08-14 at 12 58 27 PM](https://github.com/user-attachments/assets/c818295d-189f-4716-828a-473f359acf2a)

**Comment by DanielGavin** [comment]
I think it might be sublime. It doesn't happen on vscode.

If you don't want to be spammed with completion, you can just turn of the auto complete in sublime, and just have it show on ctrl+space.

**Comment by DanielGavin** [comment]
The only time vscode will show completion is when typing letters, `.`, `->`, etc.

**Comment by thetarnav** [comment]
it does happen only in sublime
but also only in odin
not sure exactly why though
when lsp is disabled, the completions are not triggered there

**Comment by DanielGavin** [comment]
It's because `:` is a trigger word when using import statements, even If I return nothing in completion for cases where it's not used in imports, sublime still shows it. Not sure why. I can't control this. 

It has be fixed on sublime side.
