### ISSUE TITLE
Failing to build on latest dev

### ISSUE THREAD

**Issue by xpyxel** [DanielGavin/ols#48]
Was trying to build on the latest [odin release](https://github.com/odin-lang/Odin/releases/tag/dev-2021-08) but it comes up with a lot of errors, i've tried to go through and fix it myself to make a PR or something, but I don't know odin well enough.

![image](https://user-images.githubusercontent.com/46457601/130349728-b968123f-e016-4528-84b7-b51eabadc36f.png)

**Comment by DanielGavin** [comment]
Yeah that is not possible. The odin release is too old, but i have executables you can download: https://github.com/DanielGavin/ols/releases.

If you are on vscode it will automatically down them for you.

**Comment by xpyxel** [comment]
Ah I see, thanks.
