### ISSUE TITLE
Segfault when using `or_else` on procedure assigned to global

### ISSUE THREAD

**Issue by FourteenBrush** [DanielGavin/ols#480]
Following code causes a segfault on neovim, linux:

![image](https://github.com/user-attachments/assets/b03cb387-aafe-4411-804b-c200bb4e6dc0)

Replacing `values` with `values()` has the same effect

**Comment by DanielGavin** [comment]
Please paste the code in a formatted string.

**Comment by FourteenBrush** [comment]
```go
package test

main :: proc() {}

values :: proc() -> (string, bool) {
    return "", true
}

global := values or_else ""
```

**Comment by DanielGavin** [comment]
Fixed.
