### ISSUE TITLE
Assertion failure src/llvm_backend_stmt.cpp

### ISSUE THREAD

**Issue by sltu** [DanielGavin/ols#484]
Hi, I got this issue when I started `build.sh` script (Debian 12, llvm14, clang 14)

```
ols on master
 
❯ ./build.sh 
src/llvm_backend_stmt.cpp(1577): Assertion Failure: `are_types_ide​‌​
ntical(e->type, value.type)` 
./build.sh: line 50: 1058026 Illegal instruction     (core dumped)​‌​
 odin build src/ -show-timings -collection:src=src -out:ols -micro​‌​
arch:native -no-bounds-check -o:speed $@
```

**Comment by DanielGavin** [comment]
This is a compiler bug.

I think it's caused by having an old llvm version. The linux build for CI is using llvm 17 and it works fine there.

**Comment by sltu** [comment]
Yes, It can be that issue.
With llvm 17, do I need to upgrade clang version to 17 also?

**Comment by DanielGavin** [comment]
I'm nearly certain you have to update clang. Pretty sure llvm was installed when you installed clang.

**Comment by DanielGavin** [comment]
But it might be possible to have multiple llvm versions on Debian. I'm not actually sure.
