### ISSUE TITLE
Curtain escape chars used in  `#load*` cause server to crash

### ISSUE THREAD

**Issue by blob1807** [DanielGavin/ols#487]
If any of the following escape chars `\e`, `\a`, `\v`, or any 3 digit num >= 200 (written as `\200`) are in the path. The server will crash with no log output in VSCode. The complier is just fine with them. 

```odin 
package main

main :: proc() {
    buf := #load_directory("\a")
    data := #load("\256_palette.png")
    hash := #load_hash("\envs", "crc64")
}
```

**Comment by DanielGavin** [comment]
Doesn't crash anymore.
