### ISSUE TITLE
hover doesn't work on constants on consecutive lines

### ISSUE THREAD

**Issue by beaumccartney** [DanielGavin/ols#495]
e.g. in this example i can hover and get info for `a` and `g` through `l`. hovering `b` through `f` doesn't show anything.

If i were to add a line between a,b,c,...f then i could hover them and get info

```go
package main

a :: int
b :: f32
c :: quaternion128
d :: 1
e :: 2
f :: 3

g :: int

h :: f32

i :: quaternion128

j :: 1

k :: 2

l :: 3
```

**Comment by DanielGavin** [comment]
Seems to be an issue with `core:odin/parser` not setting the correct column and offset end. Will have to wait for a fix, or If I have time, i'll look into it.

**Comment by beaumccartney** [comment]
i can take a look, do you have a repro of the odin parser problem?

**Comment by DanielGavin** [comment]
I'll make one tomorrow for you.

**Comment by DanielGavin** [comment]
```

import "core:fmt"
import "core:odin/ast"
import "core:odin/parser"


main :: proc() {
	p: parser.Parser

	pkg := ast.Package {
		kind = .Normal,
	}

	file := ast.File {
		pkg      = &pkg,
		src      = `
        package test
a :: int
b :: int`,
		fullpath = "test.odin",
	}
	parser.parse_file(&p, &file)

	decl_a := file.decls[0]
	decl_b := file.decls[1]

	fmt.println(decl_a.pos, decl_a.end)
	fmt.println(decl_b.pos, decl_b.end)

	fmt.printf("'%v' \n", file.src[decl_a.pos.offset:decl_a.end.offset])
	fmt.printf("'%v' \n", file.src[decl_b.pos.offset:decl_b.end.offset])
}
```

**Comment by beaumccartney** [comment]
I think I've found the problem: https://github.com/odin-lang/Odin/blob/c50eaa0b7781e65778fed57870007094690b6127/core/odin/parser/parser.odin#L3718

here p.prev_tok is a semicolon token that was inserted instead of the rhs of the "assignment"

**Comment by beaumccartney** [comment]
is the issue up? If not nw I can do it just don't want to make a duplicate issue

**Comment by DanielGavin** [comment]
yeah forgot to make the issue. You can make the issue. Thanks a lot for looking into it!

**Comment by beaumccartney** [comment]
Couple of weird things I found with the issue:

- hovering on the space after right after `b`, `c`, etc. works (also works on a)
    - even if its `a`, `b`, etc is changed to `asdf`,`bsdf`, etc hovering `s` all the way to (and including) the space after `f` works
- I can't reproduce in procedure scope or block scope, though the odin parser still returns an incorrect end offset in those cases
- hovering `a: int` in file scope works (and is subject to the same issue here), but not in struct scope

e.g. `a` and `b` can't be hovered here, but if they were just global declarations they could be
```go
foo :: struct {
    a : int,
    b : int,
}
```

**Comment by DanielGavin** [comment]
Yeah that hasn't been implemented. I didn't see any reason to show anything in the struct field, when you can literally see the types, but that might change with: https://github.com/DanielGavin/ols/issues/488

**Comment by DanielGavin** [comment]
Closing. The desired feature will first be added with #488

**Comment by beaumccartney** [comment]
Will that fix the hovering consecutive constants issue?

**Comment by DanielGavin** [comment]
I'm sorry. I thought you had fixed the issue on Odin.

**Comment by beaumccartney** [comment]
I've had a pretty busy week (Canadian thanksgiving) so I haven't been able to get around to it. I think I'm right about the problem but I'm not sure what the fix is, and to know I need to look through both core:odin and the actual compiler's parser. I'll update here when I've gotten around to it.

**Comment by DanielGavin** [comment]
Oh no hurry then. Not trying to rush you.

**Comment by beaumccartney** [comment]
the parser issue got fixed
