### ISSUE TITLE
Highlighting for `when ODIN_*` conditions with semantic tokens on, breaks on neovim

### ISSUE THREAD

**Issue by FourteenBrush** [DanielGavin/ols#502]
Note that I've only tested this on neovim:
![image](https://github.com/user-attachments/assets/e6b00972-3c79-4508-b135-b425f6eb25a5)

Copy code
<details>

```go
package whatever

import "core:log"
import "core:net"
import "core:strings"

Enum :: enum { A, B }

E :: Enum.A

LEVEL :: E when ODIN_DEBUG else E
LEVEL_B :: log.Level.Info when ODIN_DEBUG else log.Level.Error
SOMETHING_ELSE :: Enum.A when ODIN_OS == .WASI else Enum.B

WORKS_FINE :: 1 when ODIN_DEBUG else 2
ALSO_FINE :: true when ODIN_OS == .Darwin else false

Struct :: struct { x: int }

Y :: Struct {x=2} when ODIN_DEBUG else Struct{}
YB :: strings.Builder{} when ODIN_DEBUG else strings.Builder{}

Union :: union {int, f32}
Z: Union : int(2) when ODIN_ARCH ==.i386 else f32(3)
ZB: net.Address : net.IP6_Address{} when ODIN_DEBUG else net.IP4_Address{}

BitSet :: bit_set[Enum]

S: BitSet : {} when ODIN_ARCH == .wasm32 else {.A}
SA: log.Options : {.Level} when ODIN_DEBUG else {}

EnumAlias :: Enum
Set :: bit_set[EnumAlias]

BX: Set : {.A} when ODIN_DEBUG else {.A, .B}
```
</details>

Without semantic tokens in ols.json:
<details>

![image](https://github.com/user-attachments/assets/ff7a0acc-9496-437c-a8e0-0bf310e12f1d)
</details>

Those highlighting issues only seem to arise when assigning one of the following to a constant in a ternary `when`, which checks some `ODIN_*` constant:

- Enum (same or different package)
- Struct (same or different package)
- Union (same or different package)
- BitSet (different package)
(bitfields cannot be a comptime known constant)

Making a constant `ODIN_SOMETHING` however does not reproduce it.

Disabling semantic tokens makes this highlighting issue disappear

## Treesitter tokens (via `:Inspect`):

<details>

### Line 11:
Purple `O`:
![image](https://github.com/user-attachments/assets/9cde3b1b-8ce2-403d-b154-77aea954947c)

White `DIN_DEBUG`:
![image](https://github.com/user-attachments/assets/84039ddc-cbfd-4a89-91bf-e28c7adcca47)

### Line 12:
Yellow `ODI`:
![image](https://github.com/user-attachments/assets/b2391aee-a777-4996-95b5-5313c4e2ad66)

White `N`:
![image](https://github.com/user-attachments/assets/8d362c85-6756-4302-82da-71943072b60e)

Blue `_DEBU`:
![image](https://github.com/user-attachments/assets/3f813d20-c09c-4cbf-836d-74314aed30ae)

White `G`:
![image](https://github.com/user-attachments/assets/50663538-54bb-44e9-9fc6-ebc2e9cd6d42)

Purple `els`:
![image](https://github.com/user-attachments/assets/872ba5e8-0e1a-41a5-a852-833095a5193e)

Orange `e`:
![image](https://github.com/user-attachments/assets/3c139a93-2e80-4efb-8cb1-aca9ab1b3110)

### Line 13:
Purple `e`:
![image](https://github.com/user-attachments/assets/defc554f-c35f-4829-a0b2-62fd000fdb73)

Orange `lse`:
![image](https://github.com/user-attachments/assets/64c3743b-6a41-4394-8e16-e7a368067350)

In lines 15 and 16, `ODIN_DEBUG` has the same tokens as any other white part. 

</details>

## Neovim config for reference
<details>

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
--- @diagnostic disable-next-line: undefined-field
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system {
    'git',
    'clone',
    '--filter=blob:none',
    'https://github.com/folke/lazy.nvim.git',
    '--branch=stable',
    lazypath,
  }
end

vim.opt.rtp:prepend(lazypath)

require('lazy').setup {
  { 'nvim-treesitter/nvim-treesitter', build = ':TSUpdate', event = { 'BufReadPre', 'BufNewFile' } },
  { 'hrsh7th/nvim-cmp', event = { 'InsertEnter', 'CmdlineEnter', 'BufReadPost' } },
  { 'hrsh7th/cmp-nvim-lsp' },
  { 'neovim/nvim-lspconfig' },
  { 'windwp/nvim-autopairs' },
  { 'Shatur/neovim-ayu' },
}

vim.cmd.colorscheme 'ayu-dark'

--- @diagnostic disable-next-line: missing-fields
require('nvim-treesitter.configs').setup {
  highlight = { enable = true },
  ensure_installed = { 'odin' },
}

require('lspconfig').ols.setup {}

local cmp = require('cmp')
cmp.setup {
  sources = cmp.config.sources {
    { name = 'nvim_lsp' },
  },
  mapping = cmp.mapping.preset.insert {
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<Tab>'] = cmp.mapping.confirm { select = true },
    ['<S-Tab>'] = cmp.mapping(function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end),
  },
  { name = 'buffer' },
}

require('nvim-autopairs').setup { check_ts = true }
```

**Comment by thetarnav** [comment]
Not just in neovim
But in vscode I see less issues

![image](https://github.com/user-attachments/assets/2c1592b4-4220-453f-8362-5d6ea702e25d)

**Comment by DanielGavin** [comment]
Fixed. Just called them in the wrong order.
