### ISSUE TITLE
Hover resolves symbols incorrectly when matching an imported package

### ISSUE THREAD

**Issue by LnL7** [DanielGavin/ols#503]
I added a test and a partial fix here https://github.com/DanielGavin/ols/compare/master...LnL7:ols:fix/proc-same-package-hover, but given the explicit comment and the fact that local variables still don't work I suspect this isn't the right approach to resolve this issue.

<details><summary>foo/foo.odin</summary>

```odin
package foo

foo :: proc() -> string {
    return "foo"
}

bar :: proc() -> string {
    return "bar"
}
```

</details>

```odin
package example

import "foo"

main :: proc() {
	_ = foo.foo()  // hover ": package"
	_ = foo.bar()  // hover "foo.bar: proc() -> string"

	foo := 1  // hover "foo: package"
	bar := 2  // hover "example.bar: int"
}
```

![Screenshot 2024-09-15 at 10 33 07](https://github.com/user-attachments/assets/f97eeec1-5c49-4a02-9a18-1f95b5037208)

**Comment by DanielGavin** [comment]
Fixed.
