### ISSUE TITLE
Go to definition and variable type hint don't work in some cases (Objective C)

### ISSUE THREAD

**Issue by yay** [DanielGavin/ols#506]
Demo: https://github.com/user-attachments/assets/815052b5-7e14-4262-babd-880fe1b6fa9b

Steps to reproduce:

1) open this Odin example: https://github.com/odin-lang/examples/blob/master/learn_metal/02-argbuffers-no-sdl/02-argbuffers-no-sdl.odin

2) hover `setVertexFunction` while holding Cmd key inside `desc->setVertexFunction(vertex_function)` line 
    **Expected**: hovered call is underlined
    **Actual**: no underline observed

3) click `setVertexFunction` while holding Cmd key inside `desc->setVertexFunction(vertex_function)` line
    **Expected**: vscode navigates to the definition of the `setVertexFunction` call
    **Actual**: nothing happens

4) hover `desk` inside `desc->setVertexFunction(vertex_function)` line
    **Expected**: tooltip with the type of `desk` appears
    **Actual**: nothing happens

**Comment by DanielGavin** [comment]
Should be fixed. Was an issue with two `init` functions existing because there is a base `init` and the `init` overriden by RenderPipelineDescriptor.

**Comment by yay** [comment]
Amazing, thank you!
