### ISSUE TITLE
[odinfmt] Option to keep newlines

### ISSUE THREAD

**Issue by shayded-exe** [DanielGavin/ols#507]
It would be great to have an option to not remove newlines.
I really really don't like when a formatter forces my multiple lines onto a single line.

See how this:  
![image](https://github.com/user-attachments/assets/75b17fdc-7a4c-4465-856b-23383e83b2e7)

Gets reformatted to this:  
![image](https://github.com/user-attachments/assets/d27965b3-4105-4a2e-97c8-5ade2bd02837)

**Comment by DanielGavin** [comment]
That will never be possible with this formatter.
