### ISSUE TITLE
[vscode, syntax highlighting]: Unexpected highlighting for ternary expression

### ISSUE THREAD

**Issue by MichaelZalla** [DanielGavin/ols#515]
For this sample `test()` proc, syntax highlighting seems to treat `b` as a type (green) rather than as a value (blue, like `a`):

```
test :: proc() -> int {
	a, b := 2, 3
	c := a % 2 == 0 ? a : b
	return c
}
```

Is this expected?

![image](https://github.com/user-attachments/assets/6502dd24-ae11-40bb-8c65-5881935aca55)

```
danielgavin.ols@v0.1.30
```

**Comment by DanielGavin** [comment]
I have updated the extension. It should be fixed now.
@thetarnav  Had fixed it a while ago, I just forgot to update the extension.
