### ISSUE TITLE
Autocomplete is broken with in place nested struct references

### ISSUE THREAD

**Issue by kulkalkul** [DanielGavin/ols#516]
I've skimmed over all the open issues, couldn't find something existing, so here I am.

```odin
Foo :: struct {
    something: f32,
    bar: ^Bar,
}
Bar :: struct {
    something_else: i32,
}

// using somewhere
foo := Foo {
    something: 5,
    bar: &Bar {
        // autocompleting here shows "something" or "bar", not "something_else"
    },
}
```

As described above, in place references (don't know the correct term) autocompletes with top-most parent's fields. It isn't end of the world, but one place I use this is when working with Vulkan API structs, like VkGraphicsPipelineCreateInfo.

**Comment by DanielGavin** [comment]
![billede](https://github.com/user-attachments/assets/81ab4451-a6f8-4b84-9989-4cb5cfc8ac52)


Sure those aren't typos? It seems to work.

**Comment by kulkalkul** [comment]
That works, right; but isn't that syntax incorrect (lacks ampersand)? Here, I attached the behavior I'm having with both of them:
https://github.com/user-attachments/assets/4cf3d1e9-4faf-485b-9756-769c6d37a09b

I also tried this with Sublime, so I know this isn't Helix specific

**Comment by DanielGavin** [comment]
Both should be fixed.

**Comment by kulkalkul** [comment]
Ah, yeah, I'm still used to ``:`` from other languages so it happens, sorry about that.
> It does go out of stack right after the function has been called, so it can't be used anymore after that.

In Vulkan API's case I use these as configuration options that are applied the moment function is called, so it'll allow me to embed most of them into the main struct itself:
![image](https://github.com/user-attachments/assets/b0bb5ce8-1889-45b9-ad69-5059c87c1b86)


Thanks a lot.
