### ISSUE TITLE
No IntelliSense for variables assigned from generic functions if their type isn't specified.

### ISSUE THREAD

**Issue by Stannic-7863** [DanielGavin/ols#521]
Example
```odin
foo :: proc {foo_int, foo_float, foo_i32, foo_f32}
foo_val := foo()
```
No intellisense will be given for foo_val unless the type of `foo_val` is explicitly specified 

```odin
foo_val : int = foo()
```

![image](https://github.com/user-attachments/assets/9a3b0834-bdc7-4f9f-842c-68dd29cc5f5c)
![image](https://github.com/user-attachments/assets/73e57872-040e-4098-bc62-4ebf32dd43ec)

**Comment by DanielGavin** [comment]
Please specify your definitions of all the `foo_*`.

**Comment by DanielGavin** [comment]
I think your code is invalid. Have you tried compiling it? There is no way to resolve foo(), since it takes no arguments, how would Odin be able to infer what procedure to use.

**Comment by Stannic-7863** [comment]
My bad, I didn't investage enough and made conclusions

The issue seems to be exclusive to the inbuilt len function 

![image](https://github.com/user-attachments/assets/b8f72d4b-ef06-4124-b98f-1be37d5290bf)
![image](https://github.com/user-attachments/assets/ce309ed3-8973-4cfb-8000-40ac2a0e9366)

**Comment by Stannic-7863** [comment]
Its related to generic functions I suppose

```
foo :: proc(x: $T) -> T {
	return x + 1
}
```

![image](https://github.com/user-attachments/assets/9ce60b95-2314-499f-9b09-d34b2af0c155)
![image](https://github.com/user-attachments/assets/6ef0093d-01a0-4b81-9b20-4da30d3cc601)

**Comment by DanielGavin** [comment]
Should be fixed now. Tested on the builtin len and your example.
