### ISSUE TITLE
ols Breaks VSCode's Sticky Scroll

### ISSUE THREAD

**Issue by dozn** [DanielGavin/ols#524]
All scopes besides `proc`s are ignored, and it chooses to show the second `import` in files as well.

ols off:
![image](https://github.com/user-attachments/assets/2338d6a9-ee58-48d6-9e21-2ecc59bc6ace)
ols on:
![image](https://github.com/user-attachments/assets/59744a8d-fe42-4123-9367-625b352baf28)

**Comment by DanielGavin** [comment]
Not sure how to add it to vscode sticky scroll. It right now uses the outline of all the functions, but there is no way to describe it for loop, etc.

**Comment by dozn** [comment]
Huh, looks like you're correct—neither Go nor Rust support more than that either. What an odd thing for it to be supported when the language servers are disabled, and to not provide a way to express it >_<
My apologies!
