### ISSUE TITLE
Compilation doesn't work

### ISSUE THREAD

**Issue by hirochirac** [DanielGavin/ols#526]
I am trying to compile OLS. Here are the errors message below i am getting. 
OS: ubuntu 24.1
Machine: Raspberry 5

home/blegrin/bin/ols/src/common/ast.odin(80:14) Error: 'parser.Private_Flag' is not a type 
	private:    parser.Private_Flag, 
	            ^~~~~~~~~~~~~~~~~~^ 
 
/home/blegrin/bin/ols/src/odin/printer/printer.odin(218:13) Error: 'file' of type '^File' has no field 'tags' 
	for tag in file.tags { 
	           ^~~^ 
 
/home/blegrin/bin/ols/src/odin/printer/printer.odin(219:51) Error: Undeclared name: tag 
	... ns(p.document, text(strings.trim(tag.text, "\r\n")), newline(1)) 
	                                     ^~^ 
 
/home/blegrin/bin/ols/src/odin/printer/printer.odin(220:10) Error: Undeclared name: tag 
	pos := tag.pos 
	       ^~^ 
 
/home/blegrin/bin/ols/src/common/ast.odin(271:13) Error: 'parser.File_Tags' is not a type 
	file_tags: parser.File_Tags, 
	           ^~~~~~~~~~~~~~~^ 
 
/home/blegrin/bin/ols/src/common/ast.odin(312:30) Error: Invalid type 'invalid type' for implicit selector expression '.File' 
	global_expr.private = .File 
	                       ^~~^ 
 
/home/blegrin/bin/ols/src/common/ast.odin(314:30) Error: Invalid type 'invalid type' for implicit selector expression '.Package' 
	global_expr.private = .Package 
	                       ^~~~~~^ 
 
/home/blegrin/bin/ols/src/common/ast.odin(317:29) Error: Invalid type 'invalid type' for implicit selector expression '.Package' 
	global_expr.private = .Package 
	                       ^~~~~~^ 
 
/home/blegrin/bin/ols/src/common/ast.odin(324:26) Error: Invalid type 'invalid type' for implicit selector expression '.File' 
	global_expr.private = .File 
	                       ^~~^

**Comment by DanielGavin** [comment]
You need a newer version of Odin. There was change to tags in Odin recently.
