### ISSUE TITLE
[Feature Request] show whether a procedure in diverging in textDocument/signatureHelp

### ISSUE THREAD

**Issue by FourteenBrush** [DanielGavin/ols#532]
The signature for a diverging procedure currently looks like this:

![image](https://github.com/user-attachments/assets/b6b4f24f-4564-4567-8ae6-eb5495dfe3a1)

Despite it being defined as `fatal :: proc(args: ..any) -> ! `

Showing the `-> !` too  seems more appropriate to me.

Should be a simple fix somewhere in `build_procedure_symbol_signature`.

**Comment by DanielGavin** [comment]
Thanks for adding the feature! Added the code manually. I didn't want to bother to learn how to fix a PR conflict. Was way faster just adding the line and submitting it myself.
