### ISSUE TITLE
Add odinfmt setup instructions to README

### ISSUE THREAD

**Issue by thomasaarholt** [DanielGavin/ols#537]
Hello!
I helped someone on [reddit](https://www.reddit.com/r/HelixEditor/comments/1gctb2m/comment/ltz0xli/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) with setting up odinfmt in helix today. I don't use Odin myself, but thought I'd help out by installing it and seeing if I could figure out the issue.

Now, this particular issue is unrelated to their problem, but it was unclear to me how to install the `odinfmt` binary. The `build.sh` was very easy to use, but didn't tell me immediately if `odinfmt` was installed too. I figured out that I needed to run the `./odinfmt/sh` shell script, but it would be nice if the readme just told me this.

I suggest adding the following immediately after the [installation instructions in `README.md`](https://github.com/DanielGavin/ols?tab=readme-ov-file#installation):
```bash
# To install the odinfmt formatter
./odinfmt.sh
```

I am not sure how this works on Windows, so perhaps add any equivalent instructions for Windows. I am on Mac.

**Comment by DanielGavin** [comment]
Thanks for the feedback. Added instruction to intall odinfmt.
