### ISSUE TITLE
[Ols fails to build] Language server for Odin fails to build

### ISSUE THREAD

**Issue by osag1e** [DanielGavin/ols#539]
ols git:(master) ./build.sh
/Users/dgodstand/ols/src/server/workspace_symbols.odin(17:7) Error: 'os.Error' is not a type
	err: os.Error,
	     ^~~~~~~^
	Suggestion: Did you mean?
		Errno
		EROFS
		E2BIG
		dlerror
		ENOSR
		ELAST
		EIDRM
		EBUSY
		EXDEV
		ENXIO
		ETIME
		EPIPE
		EFBIG
		EAUTH
		EINTR
		ESRCH
		ELOOP
		EPERM
		__error
		EBADF
/Users/dgodstand/ols/src/server/references.odin(20:92) Error: 'os.Error' is not a type
	... > (err: os.Error, skip_dir: bool) { ...
	            ^~~~~~~^
	Suggestion: Did you mean?
		Errno
		EROFS
		E2BIG
		dlerror
		ENOSR
		ELAST
		EIDRM
		EBUSY
		EXDEV
		ENXIO
		ETIME
		EPIPE
		EFBIG
		EAUTH
		EINTR
		ESRCH
		ELOOP
		EPERM
		__error
		EBADF
/Users/dgodstand/ols/src/main.odin(26:27) Error: Cannot convert untyped value 'nil' to 'Errno' from 'untyped nil'
	return a, cast(int)(b != nil)
	                         ^~^
/Users/dgodstand/ols/src/server/references.odin(24:10) Error: Cannot assign value 'nil' of type 'untyped nil' to 'invalid type' in return statement
	return nil, false
	       ^~^
/Users/dgodstand/ols/src/server/references.odin(28:10) Error: Cannot assign value 'nil' of type 'untyped nil' to 'invalid type' in return statement
	return nil, false
	       ^~^
/Users/dgodstand/ols/src/main.odin(32:27) Error: Cannot convert untyped value 'nil' to 'Errno' from 'untyped nil'
	return a, cast(int)(b != nil)
	                         ^~^
/Users/dgodstand/ols/src/server/references.odin(38:9) Error: Cannot assign value 'nil' of type 'untyped nil' to 'invalid type' in return statement
	return nil, false
	       ^~^
/Users/dgodstand/ols/src/common/ast.odin(80:14) Error: 'Private_Flag' is not declared by 'parser'
	private:    parser.Private_Flag,
	            ^~~~~~~~~~~~~~~~~~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(134:8) Error: 'starts_with' is not declared by 'strings'
	if !strings.starts_with(comment.text, "//") do continue
	    ^~~~~~~~~~~~~~~~~~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(137:8) Error: 'starts_with' is not declared by 'strings'
	if !strings.starts_with(comment_text, "odinfmt:") do continue
	    ^~~~~~~~~~~~~~~~~~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(218:13) Error: Cannot iterate over 'file.tags' of type '^File'
	for tag in file.tags {
	           ^~~~~~~~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(219:51) Error: Undeclared name: tag
	... gs.trim(tag.text, "\r\n")), newline(1)) ...
	            ^~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(220:10) Error: Undeclared name: tag
	pos := tag.pos
	       ^~^
/Users/dgodstand/ols/src/common/ast.odin(271:13) Error: 'File_Tags' is not declared by 'parser'
	file_tags: parser.File_Tags,
	           ^~~~~~~~~~~~~~~^
/Users/dgodstand/ols/src/odin/printer/visit.odin(239:45) Error: Cannot assign value 'path' of type 'string' to '^Expr' in procedure argument
	document = cons(document, visit_expr(p, path))
	                                        ^~~^
/Users/dgodstand/ols/src/odin/printer/visit.odin(246:54) Error: Cannot assign value 'v.fullpaths[0]' of type 'string' to '^Expr' in procedure argument
	... expr(p, v.fullpaths[0])) ...
	            ^~~~~~~~~~~~~^
/Users/dgodstand/ols/src/common/ast.odin(312:30) Error: Invalid type 'invalid type' for implicit selector expression '.File'
	global_expr.private = .File
	                       ^~~^
/Users/dgodstand/ols/src/common/ast.odin(314:30) Error: Invalid type 'invalid type' for implicit selector expression '.Package'
	global_expr.private = .Package
	                       ^~~~~~^
/Users/dgodstand/ols/src/common/ast.odin(317:29) Error: Invalid type 'invalid type' for implicit selector expression '.Package'
	global_expr.private = .Package
	                       ^~~~~~^
/Users/dgodstand/ols/src/common/ast.odin(324:26) Error: Invalid type 'invalid type' for implicit selector expression '.File'
	global_expr.private = .File
	                       ^~~^
/Users/dgodstand/ols/src/common/ast.odin(327:45) Error: Invalid type 'invalid type' for implicit selector expression '.File'
	if skip_private && global_expr.private == .File {
	                                           ^~~^
/Users/dgodstand/ols/src/odin/printer/visit.odin(270:10) Error: 'v' of type '^Import_Decl' has no field 'attributes'
	if len(v.attributes) > 0 {
	       ^
/Users/dgodstand/ols/src/odin/printer/visit.odin(271:51) Error: 'v' of type '^Import_Decl' has no field 'attributes'
	... tes(p, &v.attributes, v.pos)) ...
	            ^
/Users/dgodstand/ols/src/odin/printer/printer.odin(301:15) Error: 'imp' of type '^Import_Decl' has no field 'attributes'
	for attr in imp.attributes {
	            ^~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(302:4) Error: Undeclared name: attr
	attr.pos.line = start_line + i
	^~~^
/Users/dgodstand/ols/src/odin/printer/printer.odin(303:4) Error: Undeclared name: attr
	attr.end.line = start_line + i
	^~~^
/Users/dgodstand/ols/src/common/ast.odin(349:15) Error: 'parse_file_tags' is not declared by 'parser'
	... tags := parser.parse_file_tags(file, context.temp_allocator) ...
	            ^~~~~~~~~~~~~~~~~~~~~^
	Suggestion: Did you mean?
		parse_proc_tags
/Users/dgodstand/ols/src/server/marshal.odin(359:31) Error: 'info' of type 'Type_Info_Struct' has no field 'field_count'
	for name, i in info.names[0:info.field_count] {
	                            ^~~^
/Users/dgodstand/ols/src/server/collector.odin(649:23) Error: Invalid type 'invalid type' for implicit selector expression '.File'
	if expr.private == .File {
	                    ^~~^
/Users/dgodstand/ols/src/server/collector.odin(653:23) Error: Invalid type 'invalid type' for implicit selector expression '.Package'
	if expr.private == .Package {
	                    ^~~~~~^

**Comment by DanielGavin** [comment]
You are using an old Odin version.

**Comment by osag1e** [comment]
Apologies! I will update it and try again. Thanks!

**Comment by osag1e** [comment]
➜  ols git:(master) build.sh
Total Time        -  7947.027 ms - 100.00%
initialization    -     1.273 ms -   0.01%
parse files       -    17.213 ms -   0.21%
type check        -   146.619 ms -   1.84%
LLVM API Code Gen -  7698.613 ms -  96.87%
ld-link           -    83.304 ms -   1.04%  
Updated and it works now. Thank you
