### ISSUE TITLE
No Auto completion of Odin std

### ISSUE THREAD

**Issue by jpx40** [DanielGavin/ols#541]
Hey, i have no  auto completion of Odin std. 
Odin_Root is setted.
It's more like it works sometimes and other times it fails.
I using Zed. is there a way to get debup info?

**Comment by DanielGavin** [comment]
Do you get auto completion for prodecures/variables defined in the file you are editing?

If that is the case, then it's probably your `ols.json` is wrong, or `ODIN_ROOT` is not set correctly.

**Comment by jpx40** [comment]
is there a way do get debug infos?

**Comment by DanielGavin** [comment]
Yes. Whatever `ols` logs can be seen in your editors lsp log. Not sure how that works with zed.

**Comment by jpx40** [comment]
maybe i fork the Odin extension, Debug info is not working.

**Comment by jpx40** [comment]
check it later in neovim

**Comment by DanielGavin** [comment]
When you are talking about debug info, did you mean the debug symbols when compiling Odin?

Then just do `./build.bat debug`

**Comment by jpx40** [comment]
> When you are talking about debug info, did you mean the debug symbols when compiling ols?
> 
> Then just do `./build.bat debug`

during Runtime

**Comment by abradley2** [comment]
I believe I ran into this issue, and found it wasn't logging because it was a "failed to parse file" error that was logged at the "warn" level. I wish I spent more time debugging but as soon as I saw that I assumed my Odin version had outpaced my OLS version and just updated both to latest and they're working now. 

I can't find the line that I recall logging the parse error as a warning here anymore either 🤷 

But updating Odin and OLS resolved the issue for me (specifically the language server not working for core libs)

**Comment by jpx40** [comment]
> I believe I ran into this issue, and found it wasn't logging because it was a "failed to parse file" error that was logged at the "warn" level. I wish I spent more time debugging but as soon as I saw that I assumed my Odin version had outpaced my OLS version and just updated both to latest and they're working now- but I've lost my environment to replicate.
> 
> I can't find the line that I recall logging the parse error as a warning here anymore either 🤷
> 
> But updating Odin and OLS resolved the issue for me (specifically the language server not working for core libs)

thanks sry, didn't had much information myself, i am glad that logging now works.

**Comment by jpx40** [comment]
> I believe I ran into this issue, and found it wasn't logging because it was a "failed to parse file" error that was logged at the "warn" level. I wish I spent more time debugging but as soon as I saw that I assumed my Odin version had outpaced my OLS version and just updated both to latest and they're working now- but I've lost my environment to replicate.
> 
> I can't find the line that I recall logging the parse error as a warning here anymore either 🤷
> 
> But updating Odin and OLS resolved the issue for me (specifically the language server not working for core libs)

is there already an Commit which i could test?

**Comment by jpx40** [comment]
have gotten warnings that libedit.so.2 couldn't load and that ols failed to unmarashal

**Comment by jpx40** [comment]
do u know were i could look for the bug may test some stuff, have to get debugging running first don't have much time because of uni first semsester.

**Comment by DanielGavin** [comment]
I would recommend asking for help in the Odin discord in #ols channel.

**Comment by DanielGavin** [comment]
Make sure you have the latest Odin and Ols built from source.

**Comment by jpx40** [comment]
i tried an older release of the Zed extension out it worked for me.
