### ISSUE TITLE
Helix Colors

### ISSUE THREAD

**Issue by itsmagu** [DanielGavin/ols#543]
![image](https://github.com/user-attachments/assets/06b700ef-45ef-4651-9dbf-15394f009c15)
I have a rather long function that will lose it's color on the bottom 3 rows for some reason!

**Comment by DanielGavin** [comment]
You have to paste the code. And it is most likely Odin tree-sitter, which has nothing to do with ols.

**Comment by DanielGavin** [comment]
@itsmagu Yeah that is the one for Helix editor.
