### ISSUE TITLE
Type_Info_Relative_Pointer missing in runtime due to removal from Odin repo

### ISSUE THREAD

**Issue by ThomasL81** [DanielGavin/ols#545]
Hi,
I was pulling the recent builds from both the Odin repo and the ols repo.
I could no longer compile ols on windows due to the following error:

`ols/src/server/marshal.odin(259:7) Error: 'Type_Info_Relative_Pointer' is not declared by 'runtime'
        case runtime.Type_Info_Relative_Pointer:`

In the Odin repo, I now see that yesterday (14/11) the type was removed via commit e38a080:
commit message: Remove #relative types from the compiler
[Diff commit on Odin-lang repo](https://github.com/odin-lang/Odin/commit/e38a08013e1afa1bbd7b8f90ee16cfbdfacfb13f#diff-2be46da7f855ba9af1777d8515363e5606a629e2f8823c3894f5c1e49eb3a827L182)

**Comment by DanielGavin** [comment]
Yeah that was removed. Fixed. Thanks for letting me know.
