### ISSUE TITLE
explicit procedure overloading syntax error false report

### ISSUE THREAD

**Issue by foldcat** [DanielGavin/ols#546]
this code snippet is reported to be incorrect by ols while being valid and can be compiled by odin
![Screenshot_20241116-145650_Termux](https://github.com/user-attachments/assets/5ac19a0c-f646-4c29-84b3-707df9059c65)

ols is installed via neovim mason which it simply said  `installed version nightly`

the exact codebase and said line can be found [here](https://github.com/foldcat/unit/blob/756a18f44658d034728e1f762ebbf88a625daa47/parser/tokenizer.odin#L48)

**Comment by foldcat** [comment]
![Screenshot_20241116-150452_Termux](https://github.com/user-attachments/assets/3a6b9b36-bb1c-40d7-9db6-74399be271b4)

**Comment by DanielGavin** [comment]
This is not under my control. It's `core:odin/parser` and it enforces trailling commas. You can make an issue on `Odin` that you want it to support optional trailling commas.
