### ISSUE TITLE
Issue with last version of Odin

### ISSUE THREAD

**Issue by hirochirac** [DanielGavin/ols#547]
Hi,

I tried to compile the last OLS version and I got some errors to compile on window 11.
Version of odin I use is version dev-2024-11:60bc7f53d
Below error  messages:

I:/lang/ols/src/odin/printer/printer.odin(218:13) Error: 'file' of type '^File' has no field 'tags'
        for tag in file.tags {
                   ^~~^

I:/lang/ols/src/odin/printer/printer.odin(219:51) Error: Undeclared name: tag
        ... ns(p.document, text(strings.trim(tag.text, "\r\n")), newline(1))
                                             ^~^

I:/lang/ols/src/odin/printer/printer.odin(220:10) Error: Undeclared name: tag
        pos := tag.pos
               ^~^

I:/lang/ols/src/odin/printer/visit.odin(1582:6) Error: 'v' of type '^Struct_Type' has no field 'max_field_align'
        if v.max_field_align != nil {
           ^

I:/lang/ols/src/odin/printer/visit.odin(1584:54) Error: 'v' of type '^Struct_Type' has no field 'max_field_align'
        ... ent = cons_with_nopl(document, visit_expr(p, v.max_field_align))
                                                         ^

I:/lang/ols/src/odin/printer/visit.odin(1587:6) Error: 'v' of type '^Struct_Type' has no field 'min_field_align'
        if v.min_field_align != nil {
           ^

I:/lang/ols/src/odin/printer/visit.odin(1589:54) Error: 'v' of type '^Struct_Type' has no field 'min_field_align'
        ... ent = cons_with_nopl(document, visit_expr(p, v.min_field_align))

**Comment by DanielGavin** [comment]
You need a newer version of Odin.
