### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by xyproto** [DanielGavin/ols#549]
Hi,

I am trying to package `odinfmt` as an official package for Arch Linux.

If there was a git tag named ie. `v1.0.0` it would be helpful in relation to package maintenance.

Thanks for creating `odinfmt`!

**Comment by DanielGavin** [comment]
I have now made tags that follow Odin's monthly releases. This also ensures people can go to tags that work for their Odin version when building.

**Comment by DanielGavin** [comment]
https://github.com/DanielGavin/ols/releases/tag/dev-2024-11

**Comment by xyproto** [comment]
Cool, thanks!
