### ISSUE TITLE
single test runner uses old -test-name flag

### ISSUE THREAD

**Issue by 2nafish117** [DanielGavin/ols#554]
This test runner generates a command that uses an old flag (-test-name:<name>) that does not exist in the latest odin compiler.
from the odin docs, the new way to run a single case is with 
```
odin test main -define:ODIN_TEST_NAMES=<pkg>.<name>
```

![image](https://github.com/user-attachments/assets/8fd7d22d-ffab-4523-ae7d-bbc1df6a65cc)

**Comment by 2nafish117** [comment]
I see two lines where `args.push(`-test-name:${fn}`);` would need to be updated to something like `args.push(`-define:${pkg}.${fn}`);`

one in editors/vscode/src/commands.ts:20
and editors/vscode/src/commands.ts:93

another in the build.sh:11 file

i would make a PR for this, but i dont know how to test this locally.

**Comment by DanielGavin** [comment]
This  should now be fixed.
