### ISSUE TITLE
Incorrect fomartting of comments after an if statement

### ISSUE THREAD

**Issue by nico-ec** [DanielGavin/ols#58]
As the title says, there is currently a bug with the formatting of comments after an if statement. The following comment gets duplicated.
This:
```
if true {
  return
}
// Comment
```
becomes this:
```
if true {
  return
}
// Comment // Comment
```
And subsequently, each formatting double that already doubled comment.

Edit: Also happens with `when`

**Comment by DanielGavin** [comment]
Bug in the Odin parser. I'll have to fix it and make a PR.

**Comment by DanielGavin** [comment]
Waiting on PR: https://github.com/odin-lang/Odin/pull/1347

**Comment by DanielGavin** [comment]
Fixed.
