### ISSUE TITLE
Incorrect formatting on long for loop with no body

### ISSUE THREAD

**Issue by jasonKercher** [DanielGavin/ols#60]
OS: Arch Linux

ols version: lastest commit: 2f2ea17723be24d96e9f2f3043d668561f406b7b (Start working on goto with...)
odin version dev-2021-12:9f0a30e3

Running ols via CoC in vim:
```
:call CocAction('format')
```

Converts...

```odin
@(private)
_get_next_token_from_here :: proc(self: ^Sql_Parser, here: ^u32) -> bool {
        i := here^ + 1
        if i >= u32(len(self.tokens)) {
                return true
        }
        for ; self.tokens[i].type != .Query_End && self.tokens[i].type == .Query_Comment; i += 1 {}
        here^ = i
        return self.tokens[i].type == .Query_End
}
```

into...
```odin
@(private)
_get_next_token_from_here :: proc(self: ^Sql_Parser, here: ^u32) -> bool {
        i := here^ + 1
        if i >= u32(len(self.tokens)) {
                return true
        }
        for ; self.tokens[i].type != .Query_End && self.tokens[i].type == .Query_Comment; i += 1 {}
        here^
        =
        i
        return self.tokens[i].type == .Query_End
}
```
... breaking the `here^ = i` assignment. The weird part is that this does not happen if you do almost anything with that for loop the way it is written.  I tried simplifying it to a minimal example, but everything I do to simplify it causes the issue not to happen.  Another thing that causes this issue not to occur is making the empty body multiple lines:

```
for ... {}   // issue
for ... {
} // no issue
```

**Comment by DanielGavin** [comment]
It was a mistake in the breaking of the for statement. This has now been fixed.

**Comment by jasonKercher** [comment]
> It was a mistake in the breaking of the for statement. This has now been fixed.

Thank You!!
