### ISSUE TITLE
Does it make sense to support arrays and other built-in containers with fake completion methods?

### ISSUE THREAD

**Issue by DanielGavin** [DanielGavin/ols#61]
```
buf : [dynamic]u8 = ---
buf.le // autocomplete to len(buf)
buf.app // autocomplete to append(&buf, )
```

**Comment by dmitsuki** [comment]
Years late to the party, but I think yes. This is a big pain using Odin. I don't know always the function I'm looking for, and auto complete can't help because it's not a method of the type, because there are no methods, I just have to know what I want.

**Comment by DanielGavin** [comment]
Basic support has now been implemented for it.
