### ISSUE TITLE
odinfmt doubling comments

### ISSUE THREAD

**Issue by jasonKercher** [DanielGavin/ols#63]
Hello,

ols version: pulled master (b37fc717c7ecc9a62e052c94a373fddde66352ad)
odin version dev-2021-12:9f0a30e3

The following code duplicates the `/* check for alias */` comment:
```odin
foo :: proc(self: ^bar) {
        if _get_next_token(self) {
                return
        }

        /* check for alias */
        if 1 == 1 {
                return
        }
}
```

**Comment by DanielGavin** [comment]
This is not happening to me. I fixed this exact bug on Odin parser. Make sure you have a up to date Odin version.
