### ISSUE TITLE
Add "create ols.json" to command pallet

### ISSUE THREAD

**Issue by csharpdf** [DanielGavin/ols#71]
Just so its easier :)

**Comment by DanielGavin** [comment]
I could add one. I thought it was enough that it asks on projects without a root ols.json? I'm just wondering if anyone would call it.

**Comment by csharpdf** [comment]
Well IMO it would be good for when you either accidentally remove the notification(like what I did when I made this issue lol) or when you don't want to create the json file right away.

**Comment by DanielGavin** [comment]
Should be added.
