### ISSUE TITLE
Adding docs in hover

### ISSUE THREAD

**Issue by DevinR528** [DanielGavin/ols#72]
Would a PR adding walking backward from the position of a node in the text to collect comments above proc, struct, enum, and union declarations be wanted? I have a branch but sublime kept auto formating the world so it would need to be either cleaned up or there would be a few commits of just formatting.

[this commit](https://github.com/DevinR528/ols/commit/e5483fcaf0e13abc82f0ec4fb12eaf4b91434b01)

![hover](https://user-images.githubusercontent.com/29749111/146659073-369d733b-ea6c-4bac-87c4-d8bfbde40d79.png)

**Comment by DanielGavin** [comment]
Hey. We don't actually need to do that manually. All procs, structs, enums, and union are Value_decl, The odin parser should already catch the doc comments and placed here: https://github.com/odin-lang/Odin/blob/0548db423067bce16d45af651819bf56feb5d411/core/odin/ast/ast.odin#L484

Notice how we already do that with completion 
![image](https://user-images.githubusercontent.com/5999133/146660350-569e2ac4-8491-4f75-93bd-489481cd9b0e.png)

**Comment by DevinR528** [comment]
Yeah, I did notice some things did have docs, I just could not get the "standard library" to work for anything (goto, hover, completion), which now makes sense why I didn't see docs.

**Comment by DanielGavin** [comment]
Strange relative paths should work. It atleast works on windows. I'm going to submit some code that should help to fix the local files not showing comments.

**Comment by DevinR528** [comment]
FWIW on ubuntu `~/Odin/core` didn't work but `/home/devin/Odin/core` did work :shrug:

**Comment by DanielGavin** [comment]
It's the ´~´ I assume. It doesn't seem that it supports that.

**Comment by DanielGavin** [comment]
It is now submitted, you can try and test. There might still be a bug with multi comments in the function `get_doc`

**Comment by DevinR528** [comment]
Beautiful!

Is the issue that multi-line leave the leading and trailing `/`? Other wise everything looks good! I can close (or you) unless you want to keep a record of the multi-line thing.

**Comment by DanielGavin** [comment]
I'll close it, and just open an issue if I find an example of it.
