### ISSUE TITLE
Sublime installation failed

### ISSUE THREAD

**Issue by vinodvinu** [DanielGavin/ols#73]
Hi, either I am dumb or instructions are misleading. I cannot successfully install it in Sublime text4. Steps I did
1. Installed LSP
2. Edit settings.json of LSP

This is the result.
![image](https://user-images.githubusercontent.com/8840907/147605349-07b2265f-355f-4b6b-b1dd-7c9501934535.png)

**Comment by DanielGavin** [comment]
Could indicate your command is pointing to a directory instead of /path/to/ols.exe

**Comment by DanielGavin** [comment]
Fixed via discord talk
