### ISSUE TITLE
Polymorphic functions missing comma between polymorphic variables in signature

### ISSUE THREAD

**Issue by Tetralux** [DanielGavin/ols#75]
Editors:
- Sublime [effected]
- VSCode [unknown]
---
Should be `$T, $E`:

![image](https://user-images.githubusercontent.com/1348560/147713075-4177400f-13ce-402f-bef1-bfe64f7ad201.png)

**Comment by DanielGavin** [comment]
Should be fixed.

**Comment by Tetralux** [comment]
Confirmed. 👍
