### ISSUE TITLE
Distinct types are not considered types

### ISSUE THREAD

**Issue by Tetralux** [DanielGavin/ols#76]
Editors:
- Sublime [effected]
- VSCode [unknown]
---
In the following image:
- `Distinct_Type` isn't highlighted as a type.
- `util.d` is considered a `u32`.

![image](https://user-images.githubusercontent.com/1348560/147713161-74608f5d-bf84-4634-8878-2803bc841126.png)

I'm concerned that this might be inhibiting completion from working as well as it should with distinct types, though that's been a little more tricky to get a repro for.

**Comment by DanielGavin** [comment]
Try now.

**Comment by Tetralux** [comment]
This now shows that `d` is a `util.d: Distinct_Type` 👍 

However, It still doesn't show an icon for `Distinct_Type` that indicates that it's a type.

**Comment by DanielGavin** [comment]
This is fixed.
