### ISSUE TITLE
'v, ok := maybe.?' prevents completion of 'v'

### ISSUE THREAD

**Issue by Tetralux** [DanielGavin/ols#77]
```odin

f :: proc() {
    m: Maybe(int)

    v, ok := m.?

    // cannot complete 'v' here
}
```

**Comment by Tetralux** [comment]
Note that `ok` can be completed, but it has the wrong type:
![image](https://user-images.githubusercontent.com/1348560/147717583-84306d66-bfac-47de-bfb7-f5ba869e75cd.png)

**Comment by DanielGavin** [comment]
Should be fixed. Try now.

**Comment by Tetralux** [comment]
Confirmed. 👍
