### ISSUE TITLE
Incorrect bit_set formatting behavior

### ISSUE THREAD

**Issue by Ldash4** [DanielGavin/ols#78]
Repro:

Format the following code:
```
Enum :: enum {
    Foo,
    Bar,
    Baz,
    Asd,
    Fff,
}

Bit_Set :: bit_set[Enum]

foo :: proc() {
    before_format := Bit_Set {
        // .Foo,
        .Bar,
        // .Baz,
        .Asd,
        // .Fff,
    }
}
```

The bit set is formatted as `after_format := Bit_Set{.// .Foo,Bar, .// .Baz,Asd}// .Fff,`

Note that the issue appears even in simpler cases, but it seems that there are a few separated but related formatting errors, depending on where the comments are placed.

**Comment by DanielGavin** [comment]
Should be fixed.
