### ISSUE TITLE
Formatter removes compiler directives (#type, #c_vararg etc)

### ISSUE THREAD

**Issue by khvorov45** [DanielGavin/ols#81]
This
```odin
package test

foreign import lib "some.lib"

foreign lib {
    fn :: proc(#c_vararg args: ..any) ---
}

Fn: #type proc() -> int
```
Gets formatted to
```odin
package test

foreign import lib "some.lib"

foreign lib {
	fn :: proc(args: .. any) ---
}

Fn: proc() -> int
```
Which is especially a problem with `#c_vararg` because without it the foreign function isn't called correctly

**Comment by DanielGavin** [comment]
Try now. The `#type` does not seem to be implemented in the parser currently.

**Comment by khvorov45** [comment]
Can confirm that the formatter doesn't remove `#c_vararg` anymore.
