### ISSUE TITLE
formatter inserting spaces at the end of lines

### ISSUE THREAD

**Issue by khvorov45** [DanielGavin/ols#89]
This
```odin
package main

main :: proc() {
	x := 1
	y := 2
}
```
Gets formatted to
```odin
package main

main :: proc() {
	x := 1 
	y := 2
}
```
You can't see it but there is a space after `1`. It does this to every line except the last.

**Comment by DanielGavin** [comment]
That is currently on purpose. It always ends the file with a newline. Maybe that is not necessary on windows.

**Comment by khvorov45** [comment]
Ending files with a newline is fine, this is adding trailing spaces to lines though, i.e. you get `x := 1 ` instead of just `x := 1`

**Comment by DanielGavin** [comment]
Oh sorry. I see what you mean. I'll look at it.

**Comment by DanielGavin** [comment]
Should be fixed.

**Comment by khvorov45** [comment]
can confirm
