### ISSUE TITLE
Crash when typing nested compount literals

### ISSUE THREAD

**Issue by khvorov45** [DanielGavin/ols#90]
If I type something like
```odin
Rect :: struct {
	topleft: [2]int,
}
t := Rect{{1,}}
```
ols always crashes after typing `,`
The crash is here
https://github.com/DanielGavin/ols/blob/a15c6eaad6d2d6f8af1e6cfb22dc5c59efa5d7ef/src/analysis/analysis.odin#L304
because `current_comp_lit` is `nil`

**Comment by DanielGavin** [comment]
I have made a temporary fix by exiting early if it's nil. It's most likely some issue with either my code or the parser. But I'm stuck without the test system working on Odin. I'm keeping the issue open.

**Comment by DanielGavin** [comment]
Fixed
